"""The critical protocol projection, and drift against it.

A raw hash of ``/openapi.json`` would flag every typo fix as protocol drift
and would therefore be ignored within a week. What matters is narrower: the
handful of machine-readable facts a signature's validity depends on. This
module names them, states where each one lives, says why it is critical, and
compares the live value against what Station signs for.

Where the signed lane actually lives
------------------------------------
The reference does **not** publish the ``sig`` and ``nonce`` constraints on
``schema.properties``. It hangs them off ``did``::

    schema.dependentSchemas.did = {
        "required": ["sig", "nonce"],
        "properties": {"sig": {...}, "nonce": {...}},
    }

and leaves ``properties.sig`` carrying nothing but a ``description``. The
reference explains why: a body with no ``did`` is an ordinary unsigned write,
and ``sig``/``nonce`` on one are ignored rather than validated, so publishing
their patterns unconditionally would document a constraint nothing enforces.

Stage 3 read them from ``properties`` and therefore found nothing, which is
the false "the server changed the signature format" alarm this module now
exists to not repeat. Every pointer below is verified against documents
generated by the pinned reference itself - see
``tests/security/technocore_reference/PROVENANCE.md``.

Being absent is not the same as being different
-----------------------------------------------
A field the document does not carry, and a schema shape this module does not
understand, are both reported as *unevaluable* rather than as drift. Both keep
the gate shut - the verdict is fail-closed either way - but the reason the
user reads is "protocol conformance could not be verified" rather than a claim
about what the server did. Stating "every signature will be rejected" on the
strength of a lookup that went to the wrong place is exactly the mistake that
made this module wrong the first time.

Expectations come from our own contract
---------------------------------------
The patterns are derived from :mod:`technocore_conform`, the engine that
actually signs. Copying them out of the live document would make the check
self-fulfilling: it would report "current" forever and detect nothing.

Remote values are untrusted input
---------------------------------
Authority level 1 buys accuracy, not safety. Every observed value is
truncated and stripped of control characters *for display*. The comparison
itself runs against the original, type-checked value, so a padded or
whitespace-decorated payload cannot be normalised into a match.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from enum import StrEnum
from typing import Any, Final, assert_never

from technocore_conform import (
    DID_KEY_PREFIX,
    MAX_MESSAGE_CHARS,
    MAX_NOTE_VALUE_CHARS,
    MULTIBASE_LENGTH,
    NAME_PATTERN,
    NONCE_PATTERN,
    SIGNATURE_CHARS,
    SIGNATURE_PATTERN,
)

from station_api.technocore.sources import SourceId

#: Longest observed value kept for display. Generous for a pattern, far too
#: small to be a useful smuggling channel.
MAX_OBSERVED_CHARS = 200

#: Longest prose value this module will even try to read. A description
#: beyond this is not judged - it is reported as unevaluable, because a
#: negation could be hiding past any bound we did scan.
MAX_PROSE_CHARS = 2000

#: Marker used when a document does not carry the field at all. Distinct from
#: an empty string, which would be a value the server actually published.
MISSING = "<yok>"

_INVISIBLE = frozenset({"Cc", "Cf", "Cs", "Co", "Zl", "Zp"})


class _Absent:
    """Sentinel for "the document does not carry this".

    A distinct object rather than ``None`` because ``null`` is a value a
    server can legitimately publish, and the two must not be confused.
    """

    __slots__ = ()

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return "<absent>"


ABSENT: Final = _Absent()


class DriftState(StrEnum):
    """The four states the manifest check can report."""

    #: No live check has run in this process. The starting state, every time.
    NEVER_CHECKED = "never_checked"
    #: Every critical field matches what Station signs for.
    CURRENT = "current"
    #: At least one critical field is present and differs. The gate closes.
    DRIFTED = "drifted"
    #: A required document could not be fetched or parsed, or a critical
    #: field could not be evaluated. The gate closes.
    UNAVAILABLE = "unavailable"


class Severity(StrEnum):
    CRITICAL = "critical"
    WARNING = "warning"


class FieldOutcome(StrEnum):
    """What happened to one field, distinguishing absence from difference."""

    MATCHED = "matched"
    #: Present, readable, and different. This is real drift.
    MISMATCH = "mismatch"
    #: The document does not carry the field at the documented pointer.
    MISSING = "missing"
    #: The document carries a schema shape this module cannot read safely.
    UNSUPPORTED = "unsupported"


class Compare(StrEnum):
    """How an observed value is judged against the expected one.

    Every mode is type-checked. ``"86"`` is not ``86``: a server that
    published the string would be publishing a different schema, and a
    comparison that stringified both would call them equal.
    """

    #: Exact string equality on the original value. No sweeping, no
    #: stripping: a trailing newline is a different canonical payload.
    TEXT = "text"
    #: Exact integer equality. ``bool`` is rejected explicitly - it is an
    #: ``int`` subclass, and ``True == 1``.
    NUMBER = "number"
    #: The expected string must appear in a JSON array of strings.
    MEMBER = "member"
    #: A JSON array of strings whose set equals the expected set. Used for
    #: conditional ``required``, where order carries no meaning.
    NAME_SET = "name_set"
    #: A bounded prose check: every machine token present, no negation
    #: marker anywhere. See :data:`NEGATION_MARKERS`.
    PROSE = "prose"


class Lane(StrEnum):
    """Which sub-document a field's pointer is relative to."""

    #: The document root.
    DOCUMENT = "document"
    #: The message POST request-body schema.
    MESSAGE_BODY = "message_body"
    #: The note POST request-body schema.
    NOTE_BODY = "note_body"
    #: The subschema that applies to a message body *once it carries a did*.
    MESSAGE_SIGNED = "message_signed"
    #: The same, for a note body.
    NOTE_SIGNED = "note_signed"


class Derived(StrEnum):
    """Fields computed from a lane rather than read at a pointer."""

    #: The lane exists at the method and path Station will use.
    LANE_PRESENT = "lane_present"
    #: The set of field names the signed lane makes *required*.
    SIGNED_REQUIRED = "signed_required"


# ---------------------------------------------------------------------------
# Reading a document
# ---------------------------------------------------------------------------

#: Explicit segments, never a dotted string. ``paths./r/{room}.post`` split on
#: dots is ambiguous, and resolving it by longest-key matching let a remote
#: document shadow the real location by publishing a literal key with dots in
#: it. Segments remove the ambiguity rather than guarding against it.
MESSAGE_BODY_POINTER: Final[tuple[str, ...]] = (
    "paths",
    "/r/{room}",
    "post",
    "requestBody",
    "content",
    "application/json",
    "schema",
)
NOTE_BODY_POINTER: Final[tuple[str, ...]] = (
    "paths",
    "/kv/{ns}/{key}",
    "post",
    "requestBody",
    "content",
    "application/json",
    "schema",
)

# ---------------------------------------------------------------------------
# What this module claims to understand about a schema
#
# The first version of this check named the keywords it refused - $ref, allOf,
# not, and so on - and read the ones it wanted from whatever was left. That is
# backwards, and it let three different schemas that reject every signed
# request report "current":
#
#   * ``not: {}`` inside the ``sig`` field node. The pattern and the lengths
#     were still correct, and still read, while the node as a whole matched
#     nothing at all.
#   * ``properties.sig.maxLength: 1`` unconditionally, beside the conditional
#     ``minLength: 86``. Keywords at a level are conjunctive, so both apply and
#     no string satisfies both; only the conditional one was being read.
#   * ``anyOf: [{"not": {"required": ["did"]}}]`` on the body, which forbids
#     the very field that selects the signed lane. ``anyOf`` was allowed by
#     name, on the reasoning that it could only add a constraint - true, and
#     beside the point, because a constraint it adds can reject us.
#
# The shared mistake: finding the right value somewhere does not establish
# that the schema accepts our request. So the lists below are **allow-lists**.
# A key that is not named here is not ignored - it makes the schema
# unevaluable, and the gate shuts. This is not a JSON Schema engine and does
# not try to be one; it is an explicit statement of the shapes it can read.
# ---------------------------------------------------------------------------

#: Keys that annotate and never constrain. A change to one of these is
#: documentation drift, so they are stripped before a node is judged and can
#: never raise a protocol alarm.
ANNOTATION_KEYS: Final = frozenset(
    {
        "$comment",
        "default",
        "deprecated",
        "description",
        "example",
        "examples",
        "readOnly",
        "title",
        "writeOnly",
    }
)

#: Understood on a request-body schema.
UNDERSTOOD_BODY_KEYS: Final = frozenset(
    {"type", "properties", "required", "anyOf", "dependentSchemas"}
)

#: Understood on the ``dependentSchemas.did`` node.
UNDERSTOOD_LANE_KEYS: Final = frozenset({"type", "properties", "required"})

#: Understood on a single field's schema (``sig``, ``nonce``, ``did``). Their
#: *values* are type-checked by the projected fields themselves - a
#: ``maxLength`` of ``"86"`` is a mismatch on ``signature_max_length`` - so
#: this list is only about which keywords may appear at all.
UNDERSTOOD_FIELD_KEYS: Final = frozenset({"type", "pattern", "minLength", "maxLength"})

#: Understood inside one ``anyOf`` branch.
UNDERSTOOD_BRANCH_KEYS: Final = frozenset({"required"})

#: The fields a signed request body carries. Used to decide whether an
#: ``anyOf`` branch is one a signed body can satisfy. ``from`` is absent on
#: purpose: the reference ignores it on the signed lane, so Station does not
#: have to send it and must not depend on a branch that requires it.
_SIGNED_BODY_FIELDS: Final = frozenset({"did", "sig", "nonce"})

#: Words that deny a contract rather than restate it. A description is not
#: accepted merely because the right words appear in it: "86 characters, but
#: no longer unpadded" contains every token and means the opposite.
#:
#: The list is closed and short on purpose, and it is checked against the real
#: pinned description, which says "Re-encode the raw signature *rather than*
#: editing its tail" - so "rather than" is not a marker. Neither are "no" or
#: "without", because "no padding" is a legitimate way to say unpadded.
#: ``padded`` is matched on a word boundary, which "unpadded" does not create.
NEGATION_MARKERS: Final[tuple[str, ...]] = (
    "not",
    "never",
    "no longer",
    "instead",
    "deprecated",
    "obsolete",
    "removed",
    "padded",
)


def read_pointer(document: object, segments: tuple[str, ...]) -> object:
    """Walk explicit segments. Returns :data:`ABSENT` if any is missing."""
    current: object = document
    for segment in segments:
        if not isinstance(current, dict) or segment not in current:
            return ABSENT
        current = current[segment]
    return current


def pointer_text(segments: tuple[str, ...]) -> str:
    """The segments as a JSON Pointer, for display and for the record."""
    escaped = (segment.replace("~", "~0").replace("/", "~1") for segment in segments)
    return "/" + "/".join(escaped)


@dataclass(frozen=True, slots=True)
class Reading:
    """A value read from a document, or the reason it could not be.

    ``problem`` and ``conflict`` are deliberately different answers:

    * **problem** - the schema carries something this module cannot evaluate.
      We are not entitled to say what the server did, only that we could not
      check it. Reported as ``unsupported``.
    * **conflict** - the schema was evaluated and the constraints it publishes
      contradict each other, so no request can satisfy them. That is a real,
      demonstrated finding about the document. Reported as ``mismatch``.

    Both shut the gate. The split exists so the sentence the user reads is
    true, which is the whole reason this module was rewritten once already.
    """

    value: object = ABSENT
    #: Non-empty when the shape could not be evaluated. -> unsupported
    problem: str = ""
    #: Non-empty when the shape was evaluated and contradicts itself.
    #: -> mismatch
    conflict: str = ""


@dataclass(frozen=True, slots=True)
class SignedBodyView:
    """The parts of a request-body schema a signed write has to satisfy."""

    #: The body schema itself.
    body: dict[str, Any]
    #: The ``dependentSchemas.did`` node - what applies once a did is present.
    lane: dict[str, Any]
    #: ``lane["properties"]`` - the credential field schemas.
    credentials: dict[str, Any]


def _unknown_keys(node: dict[str, Any], understood: frozenset[str]) -> list[str]:
    """Keys that are neither understood nor pure annotation."""
    return sorted(set(node) - understood - ANNOTATION_KEYS)


def _constraints(node: dict[str, Any]) -> dict[str, Any]:
    """A field node with its annotations removed."""
    return {key: value for key, value in node.items() if key not in ANNOTATION_KEYS}


def _check_field_node(node: object, where: str) -> Reading:
    """A single field's schema carries only keywords we can read.

    This is what stops ``"sig": {"pattern": ..., "not": {}}`` from passing.
    The pattern is right there and correct; the node still matches nothing.
    """
    if not isinstance(node, dict):
        return Reading(problem=f"{where} bir nesne degil")
    unknown = _unknown_keys(node, UNDERSTOOD_FIELD_KEYS)
    if unknown:
        return Reading(
            problem=f"{where} degerlendirilemeyen anahtar tasiyor: {', '.join(unknown)}"
        )
    return Reading(value=node)


def _bound(node: dict[str, Any], key: str) -> int | None:
    """A length bound, only when it is really a number."""
    value = node.get(key)
    if isinstance(value, bool) or not isinstance(value, int):
        return None
    return value


def _reconcile(
    unconditional: object, conditional: dict[str, Any], where: str
) -> Reading:
    """Constraints published at both levels apply to the same value together.

    The reference publishes ``properties.sig`` carrying a description and
    nothing else, so the usual answer is "nothing to reconcile". When the
    unconditional node does carry constraints, they are not an alternative to
    the conditional ones - both apply - and this is where ``maxLength: 1``
    beside a conditional ``minLength: 86`` is caught.

    Only three outcomes are possible, and none of them intersects regexes or
    computes a general schema conjunction:

    * an identical, repeated constraint is fine;
    * length bounds are merged, and an empty range is a **conflict**;
    * anything else this module cannot combine is a **problem**.
    """
    if not isinstance(unconditional, dict):
        return Reading(problem=f"{where} bir nesne degil")

    unknown = _unknown_keys(unconditional, UNDERSTOOD_FIELD_KEYS)
    if unknown:
        return Reading(
            problem=f"{where} degerlendirilemeyen anahtar tasiyor: {', '.join(unknown)}"
        )

    extra = _constraints(unconditional)
    if not extra:
        return Reading(value=unconditional)

    outer_type, inner_type = extra.get("type"), conditional.get("type")
    if outer_type is not None and inner_type is not None and outer_type != inner_type:
        return Reading(
            conflict=(
                f"{where}.type ({outer_type!r}) kosullu tip ({inner_type!r}) ile "
                "ayni anda saglanamaz"
            )
        )

    outer_pattern, inner_pattern = extra.get("pattern"), conditional.get("pattern")
    if (
        outer_pattern is not None
        and inner_pattern is not None
        and outer_pattern != inner_pattern
    ):
        return Reading(
            problem=(
                f"{where}.pattern kosullu kaliptan farkli; iki kalibin kesisimi "
                "degerlendirilmedi"
            )
        )

    # Both levels bound the same string, so the effective range is the
    # intersection. An empty one is a demonstrated contradiction: no value
    # satisfies the schema, which means no signature would be accepted.
    lows = [
        bound
        for bound in (
            _bound(unconditional, "minLength"),
            _bound(conditional, "minLength"),
        )
        if bound is not None
    ]
    highs = [
        bound
        for bound in (
            _bound(unconditional, "maxLength"),
            _bound(conditional, "maxLength"),
        )
        if bound is not None
    ]
    if lows and highs and max(lows) > min(highs):
        return Reading(
            conflict=(
                f"{where} uzunluk araligi bos: en az {max(lows)}, en fazla "
                f"{min(highs)}; hicbir deger ikisini birden saglayamaz"
            )
        )

    return Reading(value=unconditional)


def _check_any_of(branches: object, payload_field: str) -> Reading:
    """``anyOf`` must leave a branch a signed body can actually satisfy.

    The reference publishes ``[{"required": ["from"]}, {"required": ["did"]}]``
    - name yourself or sign - and the signed branch is the one Station takes.
    That is the only shape read here. A branch shaped differently is not
    accepted merely for sitting inside a key called ``anyOf``: the previous
    version reasoned that ``anyOf`` could only add constraints, which is true
    and beside the point, because a constraint it adds can reject us.
    """
    if not isinstance(branches, list) or not branches:
        return Reading(problem="anyOf bos veya bir liste degil")

    accepted = frozenset({*_SIGNED_BODY_FIELDS, payload_field})
    satisfiable = False
    for index, branch in enumerate(branches):
        if not isinstance(branch, dict):
            return Reading(problem=f"anyOf[{index}] bir nesne degil")
        unknown = _unknown_keys(branch, UNDERSTOOD_BRANCH_KEYS)
        if unknown:
            return Reading(
                problem=(
                    f"anyOf[{index}] degerlendirilemeyen anahtar tasiyor: "
                    f"{', '.join(unknown)}"
                )
            )
        names = branch.get("required")
        if names is None:
            satisfiable = True  # an empty branch accepts anything
            continue
        if not isinstance(names, list) or not all(
            isinstance(name, str) for name in names
        ):
            return Reading(problem=f"anyOf[{index}].required bir ad listesi degil")
        if set(names) <= accepted:
            satisfiable = True

    if not satisfiable:
        return Reading(
            conflict=(
                "anyOf dallarindan hicbiri imzali govdenin tasidigi alanlarla "
                "saglanamiyor"
            )
        )
    return Reading(value=branches)


def evaluate_signed_body(schema: object, payload_field: str) -> Reading:
    """Read a request-body schema as a whole, or refuse to.

    Returns a :class:`SignedBodyView` when every part of the schema that bears
    on a signed write is one this module can read and none of them contradict.
    Otherwise a ``problem`` (cannot evaluate) or a ``conflict`` (evaluated, and
    impossible to satisfy).

    ``payload_field`` is ``text`` on the message lane and ``value`` on the note
    lane; both lanes go through here, so neither can quietly stop being
    checked.
    """
    if not isinstance(schema, dict):
        return Reading(problem="istek govdesi semasi bir nesne degil")

    unknown = _unknown_keys(schema, UNDERSTOOD_BODY_KEYS)
    if unknown:
        return Reading(
            problem=(
                "istek govdesi degerlendirilemeyen anahtar tasiyor: "
                f"{', '.join(unknown)}"
            )
        )

    properties = schema.get("properties")
    if not isinstance(properties, dict):
        return Reading(problem="istek govdesi properties bir nesne degil")

    if "anyOf" in schema:
        branches = _check_any_of(schema["anyOf"], payload_field)
        if branches.problem or branches.conflict:
            return branches

    dependent = schema.get("dependentSchemas")
    if dependent is None:
        return Reading(problem="imzali lane kosullu semasi yok (dependentSchemas eksik)")
    if not isinstance(dependent, dict):
        return Reading(problem="dependentSchemas bir nesne degil")

    lane = dependent.get("did")
    if lane is None:
        return Reading(problem="dependentSchemas.did yok")
    if not isinstance(lane, dict):
        return Reading(problem="dependentSchemas.did bir nesne degil")

    lane_unknown = _unknown_keys(lane, UNDERSTOOD_LANE_KEYS)
    if lane_unknown:
        return Reading(
            problem=(
                "dependentSchemas.did degerlendirilemeyen anahtar tasiyor: "
                f"{', '.join(lane_unknown)}"
            )
        )

    credentials = lane.get("properties")
    if not isinstance(credentials, dict):
        return Reading(problem="dependentSchemas.did.properties bir nesne degil")

    # Every field that decides whether a signed write is accepted: the two
    # credentials inside the conditional schema, the did that selects it, and
    # whatever the body says about the same names unconditionally.
    for name in ("sig", "nonce"):
        node = credentials.get(name)
        if node is None:
            return Reading(problem=f"dependentSchemas.did.properties.{name} yok")
        checked = _check_field_node(node, f"dependentSchemas.did.properties.{name}")
        if checked.problem or checked.conflict:
            return checked

        published = properties.get(name)
        if published is not None:
            assert isinstance(node, dict)
            reconciled = _reconcile(published, node, f"properties.{name}")
            if reconciled.problem or reconciled.conflict:
                return reconciled

    did_node = properties.get("did")
    if did_node is None:
        return Reading(problem="properties.did yok")
    did_checked = _check_field_node(did_node, "properties.did")
    if did_checked.problem or did_checked.conflict:
        return did_checked

    return Reading(value=SignedBodyView(body=schema, lane=lane, credentials=credentials))

# ---------------------------------------------------------------------------
# The expected contract
#
# Derived from technocore_conform, the engine that signs. Pinned here rather
# than read from the live service on purpose: a checker that adopted whatever
# the server currently says would report "current" forever.
# ---------------------------------------------------------------------------

#: ``did:key:z6Mk`` plus the remaining base58btc characters. The alphabet is
#: base58btc - the four ambiguous glyphs are absent - and the count follows
#: from the multibase length our own did module enforces.
EXPECTED_DID_PATTERN: Final = (
    rf"^{DID_KEY_PREFIX}z6Mk[1-9A-HJ-NP-Za-km-z]{{{MULTIBASE_LENGTH - 4}}}$"
)
EXPECTED_DID_CHARS: Final = len(DID_KEY_PREFIX) + MULTIBASE_LENGTH
EXPECTED_SIGNATURE_PATTERN: Final = f"^{SIGNATURE_PATTERN}$"
EXPECTED_NONCE_PATTERN: Final = f"^{NONCE_PATTERN}$"
EXPECTED_NAME_PATTERN: Final = f"^{NAME_PATTERN}$"

#: The version of the pinned reference this projection was built against. A
#: newer service is a warning, never drift: the protocol facts above are what
#: decide whether a signature stays valid.
PINNED_SERVICE_VERSION: Final = "0.10.0"


@dataclass(frozen=True, slots=True)
class ProtocolField:
    """One fact the live service publishes, and what Station expects."""

    key: str
    label: str
    source_id: SourceId
    lane: Lane
    #: Segments relative to the lane root. Empty for a derived field.
    pointer: tuple[str, ...]
    severity: Severity
    compare: Compare
    expected: str | int | tuple[str, ...]
    #: Why a change here matters. Shown to the user, so it explains the
    #: consequence rather than restating the field name.
    rationale: str
    derived: Derived | None = None

    @property
    def json_path(self) -> str:
        """Where the value lives, as a JSON Pointer, for display."""
        root = _LANE_POINTERS[self.lane]
        if self.derived is Derived.SIGNED_REQUIRED:
            return pointer_text((*root, "dependentSchemas", "did", "required"))
        if self.derived is Derived.LANE_PRESENT:
            return pointer_text(root)
        if self.lane in (Lane.MESSAGE_SIGNED, Lane.NOTE_SIGNED):
            return pointer_text(
                (*root, "dependentSchemas", "did", "properties", *self.pointer)
            )
        return pointer_text((*root, *self.pointer))

    @property
    def expected_display(self) -> str:
        """The expectation as a string, for the API and the UI."""
        if isinstance(self.expected, tuple):
            return ", ".join(self.expected)
        return str(self.expected)


_LANE_POINTERS: Final[dict[Lane, tuple[str, ...]]] = {
    Lane.DOCUMENT: (),
    Lane.MESSAGE_BODY: MESSAGE_BODY_POINTER,
    Lane.NOTE_BODY: NOTE_BODY_POINTER,
    Lane.MESSAGE_SIGNED: MESSAGE_BODY_POINTER,
    Lane.NOTE_SIGNED: NOTE_BODY_POINTER,
}

#: The body field each lane carries beside the credentials. Needed to judge an
#: ``anyOf`` branch: a branch requiring ``text`` is one a signed message can
#: satisfy, and one requiring ``from`` is not.
_LANE_PAYLOAD_FIELD: Final[dict[Lane, str]] = {
    Lane.DOCUMENT: "",
    Lane.MESSAGE_BODY: "text",
    Lane.MESSAGE_SIGNED: "text",
    Lane.NOTE_BODY: "value",
    Lane.NOTE_SIGNED: "value",
}


def _label(prefix: str, base: str) -> str:
    """``"Note imza bicimi"`` for the note lane, ``"Imza bicimi"`` for the other.

    The lane prefix carries the capital when there is one, so the base text is
    written lowercase and capitalised only when it starts the label.
    """
    return f"{prefix}{base}" if prefix else base[0].upper() + base[1:]


def _signed_lane_fields(
    lane: Lane, prefix: str, label_prefix: str
) -> tuple[ProtocolField, ...]:
    """The constraints a signed lane must publish, for one lane.

    Written once and used for both lanes: the note lane drifting away from the
    message lane is itself a protocol change, and a copy-pasted block is how
    one of them silently stops being checked.
    """
    source = SourceId.OPENAPI
    return (
        ProtocolField(
            key=f"{prefix}signature_type",
            label=_label(label_prefix, "imza alan tipi"),
            source_id=source,
            lane=lane,
            pointer=("sig", "type"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected="string",
            rationale=(
                "Imza alani string olarak tanimli olmali. Tip degisirse sunucu "
                "imzayi bizim urettigimiz bicimde okumuyor demektir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signature_pattern",
            label=_label(label_prefix, "imza bicimi"),
            source_id=source,
            lane=lane,
            pointer=("sig", "pattern"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected=EXPECTED_SIGNATURE_PATTERN,
            rationale=(
                "Padding'siz base64url, 86 karakter, son karakter AQgw'den "
                "biri (AC-04). 64 baytlik imzanin son karakterinde dort bos "
                "bit kalir; daha genis bir kalip bu bitleri sifir olmayan "
                "imzalari da kabul eder ve sozlesmeyi oldugundan gevsek "
                "gosterir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signature_min_length",
            label=_label(label_prefix, "imza en az uzunluk"),
            source_id=source,
            lane=lane,
            pointer=("sig", "minLength"),
            severity=Severity.CRITICAL,
            compare=Compare.NUMBER,
            expected=SIGNATURE_CHARS,
            rationale=(
                "Alt sinir kalibi tamamlar. Kaybolursa sema kisa bir imzayi "
                "yalniz kalip sayesinde reddediyor olur."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signature_max_length",
            label=_label(label_prefix, "imza en fazla uzunluk"),
            source_id=source,
            lane=lane,
            pointer=("sig", "maxLength"),
            severity=Severity.CRITICAL,
            compare=Compare.NUMBER,
            expected=SIGNATURE_CHARS,
            rationale="64 baytlik Ed25519 imzasinin padding'siz base64url uzunlugu.",
        ),
        ProtocolField(
            key=f"{prefix}nonce_type",
            label=_label(label_prefix, "nonce alan tipi"),
            source_id=source,
            lane=lane,
            pointer=("nonce", "type"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected="string",
            rationale=(
                "Nonce canonical string'e string olarak girer. Sayiya donerse "
                "imzalanan baytlar degisir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}nonce_pattern",
            label=_label(label_prefix, "nonce bicimi"),
            source_id=source,
            lane=lane,
            pointer=("nonce", "pattern"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected=EXPECTED_NONCE_PATTERN,
            rationale=(
                "Nonce canonical string'in icindedir, yani imza onu kapsar. "
                "Kalip degisirse imzalanan baytlar degisir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signed_fields_required",
            label=_label(label_prefix, "zorunlu imza alanlari"),
            source_id=source,
            lane=lane,
            pointer=(),
            severity=Severity.CRITICAL,
            compare=Compare.NAME_SET,
            expected=("nonce", "sig"),
            rationale=(
                "DID tasiyan bir govdede sig ve nonce zorunlu olmali. Bu iki "
                "adin yalnizca properties altinda gorunmesi zorunlu olduklarini "
                "kanitlamaz; kosullu required kaybolursa sunucu eksik "
                "kimlik bilgisiyle gelen bir govdeyi imzali saymayabilir."
            ),
            derived=Derived.SIGNED_REQUIRED,
        ),
    )


def _did_fields(
    lane: Lane, prefix: str, label_prefix: str
) -> tuple[ProtocolField, ...]:
    """``did`` sits on ``properties`` unconditionally, on both lanes."""
    return (
        ProtocolField(
            key=f"{prefix}did_pattern",
            label=_label(label_prefix, "DID bicimi"),
            source_id=SourceId.OPENAPI,
            lane=lane,
            pointer=("properties", "did", "pattern"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected=EXPECTED_DID_PATTERN,
            rationale=(
                "Sunucunun kabul ettigi DID kalibi. Degisirse Station'in "
                "urettigi did:key artik gecerli sayilmayabilir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}did_max_length",
            label=_label(label_prefix, "DID uzunlugu"),
            source_id=SourceId.OPENAPI,
            lane=lane,
            pointer=("properties", "did", "maxLength"),
            severity=Severity.CRITICAL,
            compare=Compare.NUMBER,
            expected=EXPECTED_DID_CHARS,
            rationale=(
                "Ed25519 did:key tam 56 karakterdir; farkli bir uzunluk farkli "
                "bir sema demektir."
            ),
        ),
    )


PROTOCOL_FIELDS: tuple[ProtocolField, ...] = (
    # --- the signed lanes exist at the method and path we will use ---------
    ProtocolField(
        key="signed_message_lane",
        label="Imzali mesaj yolu",
        source_id=SourceId.OPENAPI,
        lane=Lane.MESSAGE_BODY,
        pointer=(),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="POST /r/{room}",
        rationale=(
            "Station imzali mesaji bu method ve yola gonderecek. Yol veya "
            "method degisirse imza dogru uretilse bile istek yanlis yere gider."
        ),
        derived=Derived.LANE_PRESENT,
    ),
    ProtocolField(
        key="signed_note_lane",
        label="Imzali note yolu",
        source_id=SourceId.OPENAPI,
        lane=Lane.NOTE_BODY,
        pointer=(),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="POST /kv/{ns}/{key}",
        rationale=(
            "Imzali note yolu. Mesajla ayni gerekce: kaybolursa veya tasinirsa "
            "Station'in planladigi lane artik yok demektir."
        ),
        derived=Derived.LANE_PRESENT,
    ),
    # --- what the server enforces on a signed write, on both lanes ---------
    *_did_fields(Lane.MESSAGE_BODY, "", ""),
    *_signed_lane_fields(Lane.MESSAGE_SIGNED, "", ""),
    *_did_fields(Lane.NOTE_BODY, "note_", "Note "),
    *_signed_lane_fields(Lane.NOTE_SIGNED, "note_", "Note "),
    # --- the canonical strings a signature covers --------------------------
    ProtocolField(
        key="message_signature_payload",
        label="Mesaj canonical bicimi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "message_signature_payload"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="<room>|<nonce>|<text>",
        rationale=(
            "Imzanin kapsadigi tam bayt dizisi. Alan sirasi veya ayrac "
            "degisirse Station'in imzaladigi sey sunucunun bekledigi sey olmaz."
        ),
    ),
    ProtocolField(
        key="note_signature_payload",
        label="Note canonical bicimi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "note_signature_payload"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="<namespace>|<key>|<nonce>|<value>",
        rationale="Note imzasinin kapsadigi tam bayt dizisi.",
    ),
    ProtocolField(
        key="signature_encoding",
        label="Imza kodlamasi aciklamasi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "signature_encoding"),
        severity=Severity.CRITICAL,
        compare=Compare.PROSE,
        expected="base64url 86 unpadded",
        rationale=(
            "Kodlama sozlesmesinin insan tarafi. Asil dayanak makine "
            "semasidir - imza kalibi ve min/max uzunluk; bu alan onu "
            "dogrular. Ifade yeniden yazilabilir, fakat sozlesmeyi reddeden "
            "bir cumle yalniz dogru kelimeleri tasidigi icin gecmemelidir."
        ),
    ),
    ProtocolField(
        key="identity_scheme",
        label="Kimlik semasi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "scheme"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="did:key",
        rationale=(
            "Station yalniz did:key uretir; baska bir sema desteklenmiyor "
            "demektir."
        ),
    ),
    ProtocolField(
        key="identity_algorithm",
        label="Imza algoritmasi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "algorithms"),
        severity=Severity.CRITICAL,
        compare=Compare.MEMBER,
        expected="Ed25519",
        rationale=(
            "Station yalniz Ed25519 imzalar. Listeden cikarsa imzalarimiz "
            "gecersizdir."
        ),
    ),
    ProtocolField(
        key="name_pattern",
        label="Oda/namespace/key kalibi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("conventions", "name_pattern"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected=EXPECTED_NAME_PATTERN,
        rationale=(
            "Bu allow-list canonical string'i kacislama olmadan birlestirmeyi "
            "guvenli kilan seydir: yapisal alan asla '|' iceremez."
        ),
    ),
    # --- capacity and version: real changes, but a signature stays valid ----
    ProtocolField(
        key="message_chars",
        label="Mesaj karakter siniri",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("limits", "message_chars"),
        severity=Severity.WARNING,
        compare=Compare.NUMBER,
        expected=MAX_MESSAGE_CHARS,
        rationale=(
            "Kapasite degisikligi imzayi gecersiz kilmaz; kullanicinin gormesi "
            "gereken bir farktir (kunye 14.4)."
        ),
    ),
    ProtocolField(
        key="note_chars",
        label="Note karakter siniri",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("limits", "note_chars"),
        severity=Severity.WARNING,
        compare=Compare.NUMBER,
        expected=MAX_NOTE_VALUE_CHARS,
        rationale="Mesaj siniriyla ayni gerekce.",
    ),
    ProtocolField(
        key="service_version",
        label="Servis surumu",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("version",),
        severity=Severity.WARNING,
        compare=Compare.TEXT,
        expected=PINNED_SERVICE_VERSION,
        rationale=(
            "Pinlenmis referansin surumu. Daha yeni bir servis tek basina "
            "drift degildir - kritik alanlar ayrica denetlenir - fakat "
            "gorulmesi gereken bir farktir."
        ),
    ),
)


@dataclass(frozen=True, slots=True)
class FieldObservation:
    """The verdict for one field."""

    field: ProtocolField
    observed: str
    outcome: FieldOutcome
    #: Set when the outcome is ``UNSUPPORTED``; explains what was not read.
    problem: str = ""

    @property
    def matches(self) -> bool:
        return self.outcome is FieldOutcome.MATCHED

    @property
    def is_critical_failure(self) -> bool:
        return not self.matches and self.field.severity is Severity.CRITICAL

    @property
    def is_critical_mismatch(self) -> bool:
        """A critical field that is present and genuinely different."""
        return (
            self.outcome is FieldOutcome.MISMATCH
            and self.field.severity is Severity.CRITICAL
        )

    @property
    def is_critical_unevaluable(self) -> bool:
        """A critical field we could not read. Not evidence of a change."""
        return (
            self.outcome in (FieldOutcome.MISSING, FieldOutcome.UNSUPPORTED)
            and self.field.severity is Severity.CRITICAL
        )

    @property
    def reason(self) -> str:
        """One line saying what happened, without overclaiming."""
        label = self.field.label
        if self.outcome is FieldOutcome.MISMATCH:
            if self.problem:
                return f"{label}: {self.problem}"
            return (
                f"{label}: beklenen {self.field.expected_display!r}, "
                f"gorulen {self.observed!r}"
            )
        if self.outcome is FieldOutcome.MISSING:
            return (
                f"{label}: belgede bulunamadi ({self.field.json_path}); "
                "protokol uyumu dogrulanamadi"
            )
        if self.outcome is FieldOutcome.UNSUPPORTED:
            return (
                f"{label}: sema bicimi okunamadi ({self.problem}); "
                "protokol uyumu dogrulanamadi"
            )
        return ""


@dataclass(frozen=True, slots=True)
class ProjectionResult:
    """The outcome of comparing the live documents with the expectation."""

    state: DriftState
    observations: tuple[FieldObservation, ...]
    #: Human-readable reasons the state is not ``current``.
    reasons: tuple[str, ...]

    @property
    def critical_mismatches(self) -> tuple[FieldObservation, ...]:
        """Critical fields that are present and different: real drift."""
        return tuple(item for item in self.observations if item.is_critical_mismatch)

    @property
    def critical_unevaluable(self) -> tuple[FieldObservation, ...]:
        """Critical fields that could not be read at all."""
        return tuple(item for item in self.observations if item.is_critical_unevaluable)

    @property
    def critical_failures(self) -> tuple[FieldObservation, ...]:
        """Every critical field that did not match, whatever the reason."""
        return tuple(item for item in self.observations if item.is_critical_failure)

    @property
    def warnings(self) -> tuple[FieldObservation, ...]:
        return tuple(
            item
            for item in self.observations
            if not item.matches and item.field.severity is Severity.WARNING
        )


# ---------------------------------------------------------------------------
# Display and comparison
# ---------------------------------------------------------------------------


def sweep_untrusted(text: str) -> str:
    """Replace invisible characters with a space. No truncation.

    Used before *scanning* a remote description, where a marker hiding past a
    display limit would matter. Display uses :func:`safe_display`.
    """
    return "".join(
        " " if unicodedata.category(character) in _INVISIBLE else character
        for character in text
    )


def safe_display(value: object) -> str:
    """Make a remote value safe to store, log and render.

    Control, format and separator characters become a space, and the result is
    truncated. Level-1 authority means the document is probably accurate; it
    does not mean the bytes are safe to paste into a log line or a UI.

    This is a **display** function. Nothing compares its output: sweeping and
    stripping would make a payload with a trailing newline equal to the
    canonical one, and it is not.
    """
    if isinstance(value, _Absent):
        return MISSING
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    text = (
        ",".join(safe_display(item) for item in value)
        if isinstance(value, list)
        else str(value)
    )

    swept = sweep_untrusted(text).strip()
    if len(swept) > MAX_OBSERVED_CHARS:
        return swept[:MAX_OBSERVED_CHARS] + "..."
    return swept


def _prose_matches(value: str, expected: str) -> bool:
    """Every machine token present as a word, and no negation anywhere."""
    lowered = sweep_untrusted(value).lower()
    if any(
        re.search(rf"\b{re.escape(marker)}\b", lowered) for marker in NEGATION_MARKERS
    ):
        return False
    return all(
        re.search(rf"\b{re.escape(token)}\b", lowered) for token in expected.split()
    )


def _compare(field: ProtocolField, value: object) -> bool:
    """Type-checked comparison against the original value."""
    expected = field.expected

    if field.compare is Compare.TEXT:
        return isinstance(value, str) and value == expected
    if field.compare is Compare.NUMBER:
        # bool is an int subclass and True == 1; a published `true` is not 1.
        return (
            isinstance(value, int) and not isinstance(value, bool) and value == expected
        )
    if field.compare is Compare.MEMBER:
        return isinstance(value, list) and any(
            isinstance(item, str) and item == expected for item in value
        )
    if field.compare is Compare.NAME_SET:
        if not isinstance(value, list) or not all(
            isinstance(item, str) for item in value
        ):
            return False
        return isinstance(expected, tuple) and set(value) == set(expected)
    if field.compare is Compare.PROSE:
        return (
            isinstance(value, str)
            and isinstance(expected, str)
            and _prose_matches(value, expected)
        )
    # Exhaustive. A new comparison mode fails type-checking here rather than
    # silently defaulting to "matches" or "does not match".
    assert_never(field.compare)


# ---------------------------------------------------------------------------
# Extraction
# ---------------------------------------------------------------------------


def _lane_root(field: ProtocolField, document: dict[str, Any]) -> Reading:
    """The node a field's pointer is relative to.

    Every lane field - the unconditional ones as much as the conditional ones -
    goes through :func:`evaluate_signed_body` first. A body whose combined
    meaning cannot be read, or which contradicts itself, must not hand out a
    correct-looking pattern from one corner of itself: reading the right value
    out of a schema that rejects every signed request is exactly the failure
    this evaluation exists to prevent.
    """
    if field.lane is Lane.DOCUMENT:
        return Reading(value=document)

    body = read_pointer(document, _LANE_POINTERS[field.lane])
    if isinstance(body, _Absent):
        return Reading()

    evaluated = evaluate_signed_body(body, _LANE_PAYLOAD_FIELD[field.lane])
    if evaluated.problem or evaluated.conflict:
        return evaluated
    view = evaluated.value
    if not isinstance(view, SignedBodyView):  # pragma: no cover - guaranteed
        return Reading(problem="imzali lane okunamadi")

    if field.lane not in (Lane.MESSAGE_SIGNED, Lane.NOTE_SIGNED):
        return Reading(value=view.body)
    if field.derived is Derived.SIGNED_REQUIRED:
        return Reading(value=view.lane)
    return Reading(value=view.credentials)


def _read(field: ProtocolField, document: dict[str, Any]) -> Reading:
    """Read the value a field describes, including the derived ones."""
    root = _lane_root(field, document)
    if root.problem or root.conflict or isinstance(root.value, _Absent):
        return root

    if field.derived is Derived.LANE_PRESENT:
        return Reading(value=field.expected if isinstance(root.value, dict) else ABSENT)

    if field.derived is Derived.SIGNED_REQUIRED:
        node = root.value
        if not isinstance(node, dict):  # pragma: no cover - guaranteed above
            return Reading()
        required = node.get("required")
        return Reading() if required is None else Reading(value=required)

    value = read_pointer(root.value, field.pointer)
    if (
        field.compare is Compare.PROSE
        and isinstance(value, str)
        and len(sweep_untrusted(value)) > MAX_PROSE_CHARS
    ):
        return Reading(problem="aciklama beklenenden cok uzun, degerlendirilmedi")
    return Reading(value=value)


def _observe(
    field: ProtocolField, documents: dict[SourceId, dict[str, Any]]
) -> FieldObservation:
    document = documents.get(field.source_id)
    if document is None:
        return FieldObservation(
            field=field, observed=MISSING, outcome=FieldOutcome.MISSING
        )

    reading = _read(field, document)
    if reading.conflict:
        # Evaluated, and impossible to satisfy. That is a real statement about
        # the document, so it is reported as a difference rather than as
        # "could not check".
        return FieldObservation(
            field=field,
            observed=safe_display(reading.value),
            outcome=FieldOutcome.MISMATCH,
            problem=reading.conflict,
        )
    if reading.problem:
        return FieldObservation(
            field=field,
            observed=safe_display(reading.value),
            outcome=FieldOutcome.UNSUPPORTED,
            problem=reading.problem,
        )
    if isinstance(reading.value, _Absent):
        return FieldObservation(
            field=field, observed=MISSING, outcome=FieldOutcome.MISSING
        )

    outcome = (
        FieldOutcome.MATCHED if _compare(field, reading.value) else FieldOutcome.MISMATCH
    )
    return FieldObservation(
        field=field, observed=safe_display(reading.value), outcome=outcome
    )


def project(documents: dict[SourceId, dict[str, Any]]) -> ProjectionResult:
    """Compare the live documents with the expected contract.

    ``documents`` holds only the sources that parsed. Three outcomes:

    * a critical field present and different is **drift**;
    * a critical field that could not be read is **unavailable** - the check
      did not complete, and saying more than that would be a claim about the
      server that the evidence does not support;
    * otherwise **current**, with any warnings listed beside it.

    Drift wins over unavailable: a real, readable change is the more specific
    answer and the more useful one. Either way ``manifest_current`` is false.
    """
    observations = tuple(_observe(field, documents) for field in PROTOCOL_FIELDS)

    mismatches = [item for item in observations if item.is_critical_mismatch]
    if mismatches:
        return ProjectionResult(
            state=DriftState.DRIFTED,
            observations=observations,
            reasons=tuple(item.reason for item in mismatches),
        )

    unevaluable = [item for item in observations if item.is_critical_unevaluable]
    if unevaluable:
        return ProjectionResult(
            state=DriftState.UNAVAILABLE,
            observations=observations,
            reasons=tuple(item.reason for item in unevaluable),
        )

    return ProjectionResult(
        state=DriftState.CURRENT, observations=observations, reasons=()
    )


def unavailable(reasons: tuple[str, ...]) -> ProjectionResult:
    """A verdict for a check that could not be completed."""
    return ProjectionResult(
        state=DriftState.UNAVAILABLE, observations=(), reasons=reasons
    )


__all__ = [
    "ABSENT",
    "ANNOTATION_KEYS",
    "EXPECTED_DID_CHARS",
    "EXPECTED_DID_PATTERN",
    "EXPECTED_NAME_PATTERN",
    "EXPECTED_NONCE_PATTERN",
    "EXPECTED_SIGNATURE_PATTERN",
    "MAX_OBSERVED_CHARS",
    "MAX_PROSE_CHARS",
    "MESSAGE_BODY_POINTER",
    "MISSING",
    "NEGATION_MARKERS",
    "NOTE_BODY_POINTER",
    "PINNED_SERVICE_VERSION",
    "PROTOCOL_FIELDS",
    "UNDERSTOOD_BODY_KEYS",
    "UNDERSTOOD_FIELD_KEYS",
    "UNDERSTOOD_LANE_KEYS",
    "Compare",
    "Derived",
    "DriftState",
    "FieldObservation",
    "FieldOutcome",
    "Lane",
    "ProjectionResult",
    "ProtocolField",
    "Reading",
    "Severity",
    "SignedBodyView",
    "evaluate_signed_body",
    "pointer_text",
    "project",
    "read_pointer",
    "safe_display",
    "sweep_untrusted",
    "unavailable",
]
