"""The critical protocol projection, and drift against it.

A raw hash of ``/openapi.json`` would flag every typo fix as protocol drift
and would therefore be ignored within a week. What matters is narrower: the
handful of machine-readable facts a signature's validity depends on. This
module names them, states where each one lives, says why it is critical, and
compares the live value against what Station signs for.

Where the signed lane actually lives
------------------------------------
The reference does **not** publish the ``sig`` and ``nonce`` constraints on
``schema.properties``. It hangs them off ``did``::

    schema.dependentSchemas.did = {
        "required": ["sig", "nonce"],
        "properties": {"sig": {...}, "nonce": {...}},
    }

and leaves ``properties.sig`` carrying nothing but a ``description``. The
reference explains why: a body with no ``did`` is an ordinary unsigned write,
and ``sig``/``nonce`` on one are ignored rather than validated, so publishing
their patterns unconditionally would document a constraint nothing enforces.

Stage 3 read them from ``properties`` and therefore found nothing, which is
the false "the server changed the signature format" alarm this module now
exists to not repeat. Every pointer below is verified against documents
generated by the pinned reference itself - see
``tests/security/technocore_reference/PROVENANCE.md``.

A schema is read as a whole, or not at all
------------------------------------------
Finding the right value somewhere in a schema does not establish that the
schema accepts our request. Keywords at one level are conjunctive, so a
constraint we did not read still applies - and three documents that reject
every signed write once reported "current" because of exactly that. The
keyword lists below are therefore **allow-lists**: a key this module cannot
read makes the schema unevaluable rather than invisible. See the block above
:data:`ANNOTATION_KEYS` for the three cases and why they passed.

Being absent is not the same as being different
-----------------------------------------------
A field the document does not carry, and a schema shape this module does not
understand, are both reported as *unevaluable* rather than as drift. Both keep
the gate shut - the verdict is fail-closed either way - but the reason the
user reads is "protocol conformance could not be verified" rather than a claim
about what the server did. Stating "every signature will be rejected" on the
strength of a lookup that went to the wrong place is exactly the mistake that
made this module wrong the first time.

Expectations come from our own contract
---------------------------------------
The patterns are derived from :mod:`technocore_conform`, the engine that
actually signs. Copying them out of the live document would make the check
self-fulfilling: it would report "current" forever and detect nothing.

Remote values are untrusted input
---------------------------------
Authority level 1 buys accuracy, not safety. Every observed value is
truncated and stripped of control characters *for display*. The comparison
itself runs against the original, type-checked value, so a padded or
whitespace-decorated payload cannot be normalised into a match.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from enum import StrEnum
from typing import Any, Final, assert_never, cast

from technocore_conform import (
    DID_KEY_PREFIX,
    MAX_MESSAGE_CHARS,
    MAX_NOTE_VALUE_CHARS,
    MULTIBASE_LENGTH,
    NAME_PATTERN,
    NONCE_PATTERN,
    SIGNATURE_CHARS,
    SIGNATURE_PATTERN,
)

from station_api.technocore.sources import SourceId

#: Longest observed value kept for display. Generous for a pattern, far too
#: small to be a useful smuggling channel.
MAX_OBSERVED_CHARS = 200

#: Longest pattern value this module will even try to compile. The pinned
#: contract's longest pattern is well under this; anything bigger is not a
#: constraint we evaluate.
MAX_PATTERN_CHARS = 512

#: Longest prose value this module will even try to read. A description
#: beyond this is not judged - it is reported as unevaluable, because a
#: negation could be hiding past any bound we did scan.
MAX_PROSE_CHARS = 2000

#: Marker used when a document does not carry the field at all. Distinct from
#: an empty string, which would be a value the server actually published.
MISSING = "<yok>"

_INVISIBLE = frozenset({"Cc", "Cf", "Cs", "Co", "Zl", "Zp"})


class _Absent:
    """Sentinel for "the document does not carry this".

    A distinct object rather than ``None`` because ``null`` is a value a
    server can legitimately publish, and the two must not be confused.
    """

    __slots__ = ()

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return "<absent>"


ABSENT: Final = _Absent()


class DriftState(StrEnum):
    """The four states the manifest check can report."""

    #: No live check has run in this process. The starting state, every time.
    NEVER_CHECKED = "never_checked"
    #: Every critical field matches what Station signs for.
    CURRENT = "current"
    #: At least one critical field is present and differs. The gate closes.
    DRIFTED = "drifted"
    #: A required document could not be fetched or parsed, or a critical
    #: field could not be evaluated. The gate closes.
    UNAVAILABLE = "unavailable"


class Severity(StrEnum):
    CRITICAL = "critical"
    WARNING = "warning"


class FieldOutcome(StrEnum):
    """What happened to one field, distinguishing absence from difference."""

    MATCHED = "matched"
    #: Present, readable, and different. This is real drift.
    MISMATCH = "mismatch"
    #: The document does not carry the field at the documented pointer.
    MISSING = "missing"
    #: The document carries a schema shape this module cannot read safely.
    UNSUPPORTED = "unsupported"


class Compare(StrEnum):
    """How an observed value is judged against the expected one.

    Every mode is type-checked. ``"86"`` is not ``86``: a server that
    published the string would be publishing a different schema, and a
    comparison that stringified both would call them equal.
    """

    #: Exact string equality on the original value. No sweeping, no
    #: stripping: a trailing newline is a different canonical payload.
    TEXT = "text"
    #: Exact integer equality. ``bool`` is rejected explicitly - it is an
    #: ``int`` subclass, and ``True == 1``.
    NUMBER = "number"
    #: The expected string must appear in a JSON array of strings.
    MEMBER = "member"
    #: A JSON array of strings whose set equals the expected set. Used for
    #: conditional ``required``, where order carries no meaning.
    NAME_SET = "name_set"
    #: A bounded prose check: every machine token present, no negation
    #: marker anywhere. See :data:`NEGATION_MARKERS`.
    PROSE = "prose"


class Lane(StrEnum):
    """Which sub-document a field's pointer is relative to."""

    #: The document root.
    DOCUMENT = "document"
    #: The message POST request-body schema.
    MESSAGE_BODY = "message_body"
    #: The note POST request-body schema.
    NOTE_BODY = "note_body"
    #: The subschema that applies to a message body *once it carries a did*.
    MESSAGE_SIGNED = "message_signed"
    #: The same, for a note body.
    NOTE_SIGNED = "note_signed"


class Derived(StrEnum):
    """Fields computed from a lane rather than read at a pointer."""

    #: The lane exists at the method and path Station will use.
    LANE_PRESENT = "lane_present"
    #: The set of field names the signed lane makes *required*.
    SIGNED_REQUIRED = "signed_required"
    #: A merged published length bound of the lane's payload field. Absent
    #: bounds observe as the pinned expectation, so only a real change warns.
    PAYLOAD_BOUND = "payload_bound"


# ---------------------------------------------------------------------------
# Reading a document
# ---------------------------------------------------------------------------

#: Explicit segments, never a dotted string. ``paths./r/{room}.post`` split on
#: dots is ambiguous, and resolving it by longest-key matching let a remote
#: document shadow the real location by publishing a literal key with dots in
#: it. Segments remove the ambiguity rather than guarding against it.
MESSAGE_BODY_POINTER: Final[tuple[str, ...]] = (
    "paths",
    "/r/{room}",
    "post",
    "requestBody",
    "content",
    "application/json",
    "schema",
)
NOTE_BODY_POINTER: Final[tuple[str, ...]] = (
    "paths",
    "/kv/{ns}/{key}",
    "post",
    "requestBody",
    "content",
    "application/json",
    "schema",
)

# ---------------------------------------------------------------------------
# What this module claims to understand about a schema
#
# The first version of this check named the keywords it refused - $ref, allOf,
# not, and so on - and read the ones it wanted from whatever was left. That is
# backwards, and it let three different schemas that reject every signed
# request report "current":
#
#   * ``not: {}`` inside the ``sig`` field node. The pattern and the lengths
#     were still correct, and still read, while the node as a whole matched
#     nothing at all.
#   * ``properties.sig.maxLength: 1`` unconditionally, beside the conditional
#     ``minLength: 86``. Keywords at a level are conjunctive, so both apply and
#     no string satisfies both; only the conditional one was being read.
#   * ``anyOf: [{"not": {"required": ["did"]}}]`` on the body, which forbids
#     the very field that selects the signed lane. ``anyOf`` was allowed by
#     name, on the reasoning that it could only add a constraint - true, and
#     beside the point, because a constraint it adds can reject us.
#
# The shared mistake: finding the right value somewhere does not establish
# that the schema accepts our request. So the lists below are **allow-lists**.
# A key that is not named here is not ignored - it makes the schema
# unevaluable, and the gate shuts. This is not a JSON Schema engine and does
# not try to be one; it is an explicit statement of the shapes it can read.
# ---------------------------------------------------------------------------

#: Keys that annotate and never constrain. A change to one of these is
#: documentation drift, so they are stripped before a node is judged and can
#: never raise a protocol alarm.
ANNOTATION_KEYS: Final = frozenset(
    {
        "$comment",
        "default",
        "deprecated",
        "description",
        "example",
        "examples",
        "readOnly",
        "title",
        "writeOnly",
    }
)

#: Understood on a request-body schema.
UNDERSTOOD_BODY_KEYS: Final = frozenset(
    {"type", "properties", "required", "anyOf", "dependentSchemas"}
)

#: Understood on the ``dependentSchemas.did`` node.
UNDERSTOOD_LANE_KEYS: Final = frozenset({"type", "properties", "required"})

#: Understood on a single field's schema (``sig``, ``nonce``, ``did``). Their
#: *values* are type-checked by the projected fields themselves - a
#: ``maxLength`` of ``"86"`` is a mismatch on ``signature_max_length`` - so
#: this list is only about which keywords may appear at all.
UNDERSTOOD_FIELD_KEYS: Final = frozenset({"type", "pattern", "minLength", "maxLength"})

#: Understood inside one ``anyOf`` branch.
UNDERSTOOD_BRANCH_KEYS: Final = frozenset({"required"})

#: The fields a signed request body carries. Used to decide whether an
#: ``anyOf`` branch is one a signed body can satisfy. ``from`` is absent on
#: purpose: the reference ignores it on the signed lane, so Station does not
#: have to send it and must not depend on a branch that requires it.
_SIGNED_BODY_FIELDS: Final = frozenset({"did", "sig", "nonce"})

#: Words that deny a contract rather than restate it. A description is not
#: accepted merely because the right words appear in it: "86 characters, but
#: no longer unpadded" contains every token and means the opposite.
#:
#: The list is closed and short on purpose, and it is checked against the real
#: pinned description, which says "Re-encode the raw signature *rather than*
#: editing its tail" - so "rather than" is not a marker. Neither are "no" or
#: "without", because "no padding" is a legitimate way to say unpadded.
#: ``padded`` is matched on a word boundary, which "unpadded" does not create.
NEGATION_MARKERS: Final[tuple[str, ...]] = (
    "not",
    "never",
    "no longer",
    "instead",
    "deprecated",
    "obsolete",
    "removed",
    "padded",
)


def read_pointer(document: object, segments: tuple[str, ...]) -> object:
    """Walk explicit segments. Returns :data:`ABSENT` if any is missing."""
    current: object = document
    for segment in segments:
        if not isinstance(current, dict) or segment not in current:
            return ABSENT
        current = current[segment]
    return current


def pointer_text(segments: tuple[str, ...]) -> str:
    """The segments as a JSON Pointer, for display and for the record."""
    escaped = (segment.replace("~", "~0").replace("/", "~1") for segment in segments)
    return "/" + "/".join(escaped)


@dataclass(frozen=True, slots=True)
class Reading:
    """A value read from a document, or the reason it could not be.

    ``problem`` and ``conflict`` are deliberately different answers:

    * **problem** - the schema carries something this module cannot evaluate.
      We are not entitled to say what the server did, only that we could not
      check it. Reported as ``unsupported``.
    * **conflict** - the schema was evaluated and the constraints it publishes
      contradict each other, so no request can satisfy them. That is a real,
      demonstrated finding about the document. Reported as ``mismatch``.

    Both shut the gate. The split exists so the sentence the user reads is
    true, which is the whole reason this module was rewritten once already.
    """

    value: object = ABSENT
    #: Non-empty when the shape could not be evaluated. -> unsupported
    problem: str = ""
    #: Non-empty when the shape was evaluated and contradicts itself.
    #: -> mismatch
    conflict: str = ""


@dataclass(frozen=True, slots=True)
class SignedBodyView:
    """The parts of a request-body schema a signed write has to satisfy."""

    #: The body schema itself.
    body: dict[str, Any]
    #: The ``dependentSchemas.did`` node - what applies once a did is present.
    lane: dict[str, Any]
    #: ``lane["properties"]`` - the credential field schemas.
    credentials: dict[str, Any]
    #: The merged published length bounds of the payload field (``text`` or
    #: ``value``), ``None`` where no bound is published at any level. The
    #: charter (14.4) treats capacity limits as runtime data, never as
    #: hard-coded constants: these are what the composer must enforce on the
    #: real request, and what the payload-bound warning fields observe.
    payload_low: int | None = None
    payload_high: int | None = None


def _unknown_keys(node: dict[str, Any], understood: frozenset[str]) -> list[str]:
    """Keys that are neither understood nor pure annotation."""
    return sorted(set(node) - understood - ANNOTATION_KEYS)


def _read_type(node: dict[str, Any], where: str) -> Reading:
    """``type`` if present, checked as a value rather than as a name.

    Absent is fine - the reference does not put a ``type`` on every node. A
    ``type`` that is not a string is a malformed schema, not a missing key:
    ``null``, ``0`` and ``false`` all mean something specific in JSON and none
    of them is a type.
    """
    if "type" not in node:
        return Reading(value=None)
    published = node["type"]
    if not isinstance(published, str):
        return Reading(problem=f"{where}.type bir string degil: {published!r}")
    return Reading(value=published)


def _read_name_list(node: dict[str, Any], key: str, where: str) -> Reading:
    """A list-of-names keyword, checked as a value.

    ``required: null`` is not the same as no ``required`` at all, and treating
    the two alike is how a malformed schema slipped through as valid.
    """
    if key not in node:
        return Reading(value=None)
    published = node[key]
    if not isinstance(published, list) or not all(
        isinstance(name, str) for name in published
    ):
        return Reading(problem=f"{where}.{key} bir ad listesi degil: {published!r}")
    if len(set(published)) != len(published):
        # JSON Schema requires the names to be unique. A duplicate does not
        # change what the keyword means, but a document that breaks its own
        # metaschema is not one this module claims to have read correctly.
        return Reading(problem=f"{where}.{key} tekrarli ad iceriyor: {published!r}")
    return Reading(value=published)


def _read_bound(node: dict[str, Any], key: str, where: str) -> Reading:
    """A length bound, checked as a value.

    Returning "no bound" for a malformed one would be the dangerous reading:
    ``maxLength: "1"`` would then look like no ceiling at all. ``bool`` is
    rejected explicitly because it is an ``int`` subclass in Python and
    ``True == 1``; a published ``true`` is not a length.
    """
    if key not in node:
        return Reading(value=None)
    published = node[key]
    if isinstance(published, bool) or not isinstance(published, int):
        return Reading(problem=f"{where}.{key} bir sayi degil: {published!r}")
    if published < 0:
        return Reading(problem=f"{where}.{key} negatif: {published!r}")
    return Reading(value=published)


def _check_field_node(node: object, where: str) -> Reading:
    """One field's schema: allowed keywords, and every value they carry.

    Naming the keywords was only half of it. ``pattern: null`` and
    ``maxLength: "1"`` both sit under allowed names and neither is a
    constraint this module can honour, so both make the node unreadable.
    """
    if not isinstance(node, dict):
        return Reading(problem=f"{where} bir nesne degil")

    unknown = _unknown_keys(node, UNDERSTOOD_FIELD_KEYS)
    if unknown:
        return Reading(
            problem=f"{where} degerlendirilemeyen anahtar tasiyor: {', '.join(unknown)}"
        )

    published_type = _read_type(node, where)
    if published_type.problem:
        return published_type

    if "pattern" in node:
        pattern = node["pattern"]
        if not isinstance(pattern, str):
            return Reading(problem=f"{where}.pattern bir string degil: {pattern!r}")
        if len(pattern) > MAX_PATTERN_CHARS:
            return Reading(
                problem=f"{where}.pattern beklenmedik uzunlukta, degerlendirilmedi"
            )
        try:
            # Compiled only, never executed against remote-chosen input: a
            # pattern that does not even compile is an unusable schema, and
            # saying "could not read it" beats letting it pass as if it
            # constrained nothing.
            re.compile(pattern)
        except re.error as exc:
            return Reading(problem=f"{where}.pattern derlenemiyor: {exc}")

    for key in ("minLength", "maxLength"):
        bound = _read_bound(node, key, where)
        if bound.problem:
            return bound

    return Reading(value=node)


@dataclass(frozen=True, slots=True)
class _Constraint:
    """One field's effective schema, gathered from every level that applies."""

    types: tuple[str, ...] = ()
    patterns: tuple[str, ...] = ()
    lows: tuple[int, ...] = ()
    highs: tuple[int, ...] = ()
    origins: tuple[str, ...] = ()

    def merge(self, node: dict[str, Any], where: str) -> _Constraint:
        published = node.get("type")
        pattern = node.get("pattern")
        low = node.get("minLength")
        high = node.get("maxLength")
        return _Constraint(
            types=(*self.types, *((published,) if isinstance(published, str) else ())),
            patterns=(*self.patterns, *((pattern,) if isinstance(pattern, str) else ())),
            lows=(
                *self.lows,
                *((low,) if isinstance(low, int) and not isinstance(low, bool) else ()),
            ),
            highs=(
                *self.highs,
                *(
                    (high,)
                    if isinstance(high, int) and not isinstance(high, bool)
                    else ()
                ),
            ),
            origins=(*self.origins, where),
        )


def _judge_constraint(name: str, merged: _Constraint) -> Reading:
    """Can the value Station actually sends satisfy this field's schema?

    Every level that applies has been folded in, so the question is finally
    answerable. Three ways it can fail:

    * two different ``type`` values - nothing satisfies both;
    * two different ``pattern`` values - the intersection is a regex problem
      this module does not solve, so it says so rather than guessing;
    * a length range that excludes what Station sends. That is the check the
      earlier version could not make: a bound is not wrong for being unusual,
      it is wrong for excluding every value we would put in the field.
    """
    distinct_types = set(merged.types)
    if len(distinct_types) > 1:
        return Reading(
            conflict=(
                f"{name}: iki farkli tip ayni anda saglanamaz "
                f"({', '.join(sorted(distinct_types))})"
            )
        )
    if distinct_types and distinct_types != {"string"}:
        return Reading(
            conflict=(
                f"{name}: tip {next(iter(distinct_types))!r}, Station bu alani "
                "string olarak gonderir"
            )
        )

    if len(set(merged.patterns)) > 1:
        return Reading(
            problem=(
                f"{name}: birden fazla farkli kalip yayimlanmis; kesisimleri "
                "degerlendirilmedi"
            )
        )

    low = max(merged.lows) if merged.lows else 0
    high = min(merged.highs) if merged.highs else None

    # An empty range needs no knowledge of what we send: *no* value satisfies
    # it. Checking this only for the fields whose length we happen to know
    # would leave the payload fields - `text` and `value` - able to publish a
    # contradiction unnoticed, which is the same family of gap again.
    if high is not None and low > high:
        return Reading(
            conflict=(
                f"{name}: uzunluk araligi bos (en az {low}, en fazla {high}); "
                "hicbir deger ikisini birden saglayamaz"
            )
        )

    sent = STATION_FIELD_LENGTHS.get(name)
    if sent is None:
        # A payload field. Its length varies with what the user writes, so a
        # published bound is not a contract violation - the charter (14.4)
        # classifies capacity limits as a warning, surfaced and then enforced
        # on the real request - but a *pattern* here is different: we cannot
        # decide what an arbitrary regex accepts of arbitrary user text, and
        # the pinned contract publishes none, so any pattern on a payload
        # field is a constraint this module cannot evaluate.
        if merged.patterns:
            return Reading(
                problem=(
                    f"{name}: payload alaninda kalip yayimlanmis; hangi "
                    "metinleri kabul ettigi degerlendirilemedi"
                )
            )
        return Reading(value=merged)

    # Excluding SOME of what Station legitimately sends is already a refused
    # request, not just excluding all of it. A nonce is one to nineteen
    # digits and every length in that range is a value Station really
    # produces (a counter starts small; a millisecond clock is ~13 digits),
    # so a published bound must cover the whole range. For did and sig the
    # range is a single length and this reduces to the earlier total
    # exclusion check.
    if low > sent.minimum:
        return Reading(
            conflict=(
                f"{name}: en az {low} karakter isteniyor; Station'in mesru "
                f"degerleri {sent.minimum} karaktere kadar iner"
            )
        )
    if high is not None and high < sent.maximum:
        return Reading(
            conflict=(
                f"{name}: en fazla {high} karaktere izin veriliyor; Station'in "
                f"mesru degerleri {sent.maximum} karaktere kadar cikar"
            )
        )
    return Reading(value=merged)


def _check_any_of(branches: object, fields: frozenset[str]) -> Reading:
    """``anyOf`` must leave a branch a signed body can actually satisfy.

    The reference publishes ``[{"required": ["from"]}, {"required": ["did"]}]``
    - name yourself or sign - and Station takes the signed branch. That is the
    only shape read here. A branch is not accepted for sitting inside a key
    called ``anyOf``: the constraint ``anyOf`` adds can reject us.
    """
    if not isinstance(branches, list) or not branches:
        return Reading(problem="anyOf bos veya bir liste degil")

    satisfiable = False
    for index, branch in enumerate(branches):
        where = f"anyOf[{index}]"
        if not isinstance(branch, dict):
            return Reading(problem=f"{where} bir nesne degil")
        unknown = _unknown_keys(branch, UNDERSTOOD_BRANCH_KEYS)
        if unknown:
            return Reading(
                problem=(
                    f"{where} degerlendirilemeyen anahtar tasiyor: {', '.join(unknown)}"
                )
            )
        names = _read_name_list(branch, "required", where)
        if names.problem:
            return names
        if names.value is None:
            satisfiable = True  # an empty branch accepts anything
        elif set(cast("list[str]", names.value)) <= fields:
            satisfiable = True

    if not satisfiable:
        return Reading(
            conflict=(
                "anyOf dallarindan hicbiri imzali govdenin tasidigi alanlarla "
                "saglanamiyor"
            )
        )
    return Reading(value=branches)


def _check_object_node(
    node: dict[str, Any], understood: frozenset[str], fields: frozenset[str], where: str
) -> Reading:
    """``type`` and ``required`` on a body-shaped node, as values.

    Used for the request body and for every conditional subschema a signed
    body switches on, because ``dependentSchemas`` applies its subschema to
    the *whole* body - a ``type`` or ``required`` in there is as binding as
    one written at the top.
    """
    unknown = _unknown_keys(node, understood)
    if unknown:
        return Reading(
            problem=f"{where} degerlendirilemeyen anahtar tasiyor: {', '.join(unknown)}"
        )

    published = _read_type(node, where)
    if published.problem:
        return published
    if published.value is not None and published.value != "object":
        return Reading(
            conflict=(
                f"{where}.type {published.value!r}, Station bir JSON nesnesi gonderir"
            )
        )

    required = _read_name_list(node, "required", where)
    if required.problem:
        return required
    if required.value is not None:
        missing = sorted(set(cast("list[str]", required.value)) - fields)
        if missing:
            return Reading(
                conflict=(
                    f"{where}.required Station'in gondermedigi alani zorunlu "
                    f"kiliyor: {', '.join(missing)}"
                )
            )

    properties = node.get("properties")
    if properties is not None and not isinstance(properties, dict):
        return Reading(problem=f"{where}.properties bir nesne degil")

    return Reading(value=node)


def evaluate_signed_body(schema: object, fields: frozenset[str]) -> Reading:
    """Read a request-body schema as a whole, or refuse to.

    ``fields`` is the set of names Station will actually put in a signed body,
    derived from our own contract rather than from the document. Everything
    below is judged against it: a constraint is not wrong for being unusual,
    it is wrong for rejecting what we would send.

    Returns a :class:`SignedBodyView` when every part of the schema that bears
    on a signed write is one this module can read, and none of them rejects
    us. Otherwise a ``problem`` (cannot evaluate - the schema is malformed or
    uses a form outside the supported shape) or a ``conflict`` (evaluated, and
    our request would be refused).
    """
    if not isinstance(schema, dict):
        return Reading(problem="istek govdesi semasi bir nesne degil")

    body = _check_object_node(schema, UNDERSTOOD_BODY_KEYS, fields, "istek govdesi")
    if body.problem or body.conflict:
        return body

    properties = schema.get("properties")
    if not isinstance(properties, dict):
        return Reading(problem="istek govdesi properties bir nesne degil")

    if "anyOf" in schema:
        branches = _check_any_of(schema["anyOf"], fields)
        if branches.problem or branches.conflict:
            return branches

    dependent = schema.get("dependentSchemas")
    if dependent is None:
        return Reading(problem="imzali lane kosullu semasi yok (dependentSchemas eksik)")
    if not isinstance(dependent, dict):
        return Reading(problem="dependentSchemas bir nesne degil")

    lane = dependent.get("did")
    if lane is None:
        return Reading(problem="dependentSchemas.did yok")

    # Every dependency keyed on a field the signed body carries switches on.
    # Reading only `did` was the gap: a signed body also carries `sig`, `nonce`
    # and its payload field, so a dependency on any of those applies to us just
    # as hard.
    applicable: list[dict[str, Any]] = []
    for name in sorted(set(dependent) & fields):
        where = f"dependentSchemas.{name}"
        subschema = dependent[name]
        if not isinstance(subschema, dict):
            return Reading(problem=f"{where} bir nesne degil")
        checked = _check_object_node(subschema, UNDERSTOOD_LANE_KEYS, fields, where)
        if checked.problem or checked.conflict:
            return checked
        applicable.append(subschema)

    if not isinstance(lane, dict):  # pragma: no cover - the loop above covers it
        return Reading(problem="dependentSchemas.did bir nesne degil")
    credentials = lane.get("properties")
    if not isinstance(credentials, dict):
        return Reading(problem="dependentSchemas.did.properties bir nesne degil")

    # null and absent are different answers (see _Absent). A member that is
    # present but null is a malformed schema, not a missing one, and neither
    # may slip through as "nothing published here".
    for name in ("sig", "nonce"):
        if name not in credentials:
            return Reading(problem=f"dependentSchemas.did.properties.{name} yok")
        if credentials[name] is None:
            return Reading(
                problem=f"dependentSchemas.did.properties.{name} null - gecersiz sema uyesi"
            )
    if "did" not in properties:
        return Reading(problem="properties.did yok")
    if properties["did"] is None:
        return Reading(problem="properties.did null - gecersiz sema uyesi")

    # Gather every schema that applies to each field Station sends: the
    # unconditional one and one per triggered dependency. Reading only the
    # names we expected to find there is what let a `did` inside the
    # conditional properties carry a `not` unnoticed.
    payload_low: int | None = None
    payload_high: int | None = None
    credential_names = frozenset(STATION_FIELD_LENGTHS)

    for name in sorted(fields):
        merged = _Constraint()
        sources: list[tuple[object, str]] = []
        if name in properties:
            published = properties[name]
            if published is None:
                return Reading(problem=f"properties.{name} null - gecersiz sema uyesi")
            sources.append((published, f"properties.{name}"))
        for index, subschema in enumerate(applicable):
            nested = subschema.get("properties")
            if isinstance(nested, dict) and name in nested:
                node = nested[name]
                if node is None:
                    return Reading(
                        problem=(
                            f"kosullu[{index}].properties.{name} null - "
                            "gecersiz sema uyesi"
                        )
                    )
                sources.append((node, f"kosullu[{index}].properties.{name}"))

        for node, where in sources:
            checked = _check_field_node(node, where)
            if checked.problem or checked.conflict:
                return checked
            merged = merged.merge(cast("dict[str, Any]", node), where)

        if merged.origins:
            judged = _judge_constraint(name, merged)
            if judged.problem or judged.conflict:
                return judged

        if name not in credential_names:
            payload_low = max(merged.lows) if merged.lows else None
            payload_high = min(merged.highs) if merged.highs else None

    return Reading(
        value=SignedBodyView(
            body=schema,
            lane=lane,
            credentials=credentials,
            payload_low=payload_low,
            payload_high=payload_high,
        )
    )

# ---------------------------------------------------------------------------
# The expected contract
#
# Derived from technocore_conform, the engine that signs. Pinned here rather
# than read from the live service on purpose: a checker that adopted whatever
# the server currently says would report "current" forever.
# ---------------------------------------------------------------------------

#: ``did:key:z6Mk`` plus the remaining base58btc characters. The alphabet is
#: base58btc - the four ambiguous glyphs are absent - and the count follows
#: from the multibase length our own did module enforces.
EXPECTED_DID_PATTERN: Final = (
    rf"^{DID_KEY_PREFIX}z6Mk[1-9A-HJ-NP-Za-km-z]{{{MULTIBASE_LENGTH - 4}}}$"
)
EXPECTED_DID_CHARS: Final = len(DID_KEY_PREFIX) + MULTIBASE_LENGTH
EXPECTED_SIGNATURE_PATTERN: Final = f"^{SIGNATURE_PATTERN}$"
EXPECTED_NONCE_PATTERN: Final = f"^{NONCE_PATTERN}$"
EXPECTED_NAME_PATTERN: Final = f"^{NAME_PATTERN}$"

#: The version of the pinned reference this projection was built against. A
#: newer service is a warning, never drift: the protocol facts above are what
#: decide whether a signature stays valid.
PINNED_SERVICE_VERSION: Final = "0.10.0"

#: The digit counts ``NONCE_PATTERN`` allows. A test pins these against the
#: pattern itself so the two cannot drift apart.
NONCE_MIN_DIGITS: Final = 1
NONCE_MAX_DIGITS: Final = 19


@dataclass(frozen=True, slots=True)
class SentLength:
    """How long the value Station puts in a field can be."""

    minimum: int
    maximum: int


#: What Station actually sends, from our own contract rather than from the
#: document. A published bound is not wrong for being unusual - it is wrong
#: for excluding every value we would put in the field, and that comparison
#: needs a number from *our* side of the protocol.
STATION_FIELD_LENGTHS: Final[dict[str, SentLength]] = {
    "did": SentLength(EXPECTED_DID_CHARS, EXPECTED_DID_CHARS),
    "sig": SentLength(SIGNATURE_CHARS, SIGNATURE_CHARS),
    "nonce": SentLength(NONCE_MIN_DIGITS, NONCE_MAX_DIGITS),
}

#: The field names a signed request body carries, per lane. The credentials
#: are the same on both; the payload field is not. Everything the evaluator
#: judges is judged against this set: a schema that requires a name absent
#: here is a schema our request cannot satisfy.
PLANNED_BODY_FIELDS: Final[dict[Lane, frozenset[str]]] = {
    Lane.MESSAGE_BODY: frozenset({"did", "sig", "nonce", "text"}),
    Lane.MESSAGE_SIGNED: frozenset({"did", "sig", "nonce", "text"}),
    Lane.NOTE_BODY: frozenset({"did", "sig", "nonce", "value"}),
    Lane.NOTE_SIGNED: frozenset({"did", "sig", "nonce", "value"}),
}


@dataclass(frozen=True, slots=True)
class ProtocolField:
    """One fact the live service publishes, and what Station expects."""

    key: str
    label: str
    source_id: SourceId
    lane: Lane
    #: Segments relative to the lane root. Empty for a derived field.
    pointer: tuple[str, ...]
    severity: Severity
    compare: Compare
    expected: str | int | tuple[str, ...]
    #: Why a change here matters. Shown to the user, so it explains the
    #: consequence rather than restating the field name.
    rationale: str
    derived: Derived | None = None

    @property
    def json_path(self) -> str:
        """Where the value lives, as a JSON Pointer, for display."""
        root = _LANE_POINTERS[self.lane]
        if self.derived is Derived.SIGNED_REQUIRED:
            return pointer_text((*root, "dependentSchemas", "did", "required"))
        if self.derived is Derived.LANE_PRESENT:
            return pointer_text(root)
        if self.derived is Derived.PAYLOAD_BOUND:
            payload = next(iter(PLANNED_BODY_FIELDS[self.lane] - frozenset(STATION_FIELD_LENGTHS)))
            return pointer_text((*root, "properties", payload, *self.pointer))
        if self.lane in (Lane.MESSAGE_SIGNED, Lane.NOTE_SIGNED):
            return pointer_text(
                (*root, "dependentSchemas", "did", "properties", *self.pointer)
            )
        return pointer_text((*root, *self.pointer))

    @property
    def expected_display(self) -> str:
        """The expectation as a string, for the API and the UI."""
        if isinstance(self.expected, tuple):
            return ", ".join(self.expected)
        return str(self.expected)


_LANE_POINTERS: Final[dict[Lane, tuple[str, ...]]] = {
    Lane.DOCUMENT: (),
    Lane.MESSAGE_BODY: MESSAGE_BODY_POINTER,
    Lane.NOTE_BODY: NOTE_BODY_POINTER,
    Lane.MESSAGE_SIGNED: MESSAGE_BODY_POINTER,
    Lane.NOTE_SIGNED: NOTE_BODY_POINTER,
}



def _label(prefix: str, base: str) -> str:
    """``"Note imza bicimi"`` for the note lane, ``"Imza bicimi"`` for the other.

    The lane prefix carries the capital when there is one, so the base text is
    written lowercase and capitalised only when it starts the label.
    """
    return f"{prefix}{base}" if prefix else base[0].upper() + base[1:]


def _signed_lane_fields(
    lane: Lane, prefix: str, label_prefix: str
) -> tuple[ProtocolField, ...]:
    """The constraints a signed lane must publish, for one lane.

    Written once and used for both lanes: the note lane drifting away from the
    message lane is itself a protocol change, and a copy-pasted block is how
    one of them silently stops being checked.
    """
    source = SourceId.OPENAPI
    return (
        ProtocolField(
            key=f"{prefix}signature_type",
            label=_label(label_prefix, "imza alan tipi"),
            source_id=source,
            lane=lane,
            pointer=("sig", "type"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected="string",
            rationale=(
                "Imza alani string olarak tanimli olmali. Tip degisirse sunucu "
                "imzayi bizim urettigimiz bicimde okumuyor demektir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signature_pattern",
            label=_label(label_prefix, "imza bicimi"),
            source_id=source,
            lane=lane,
            pointer=("sig", "pattern"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected=EXPECTED_SIGNATURE_PATTERN,
            rationale=(
                "Padding'siz base64url, 86 karakter, son karakter AQgw'den "
                "biri (AC-04). 64 baytlik imzanin son karakterinde dort bos "
                "bit kalir; daha genis bir kalip bu bitleri sifir olmayan "
                "imzalari da kabul eder ve sozlesmeyi oldugundan gevsek "
                "gosterir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signature_min_length",
            label=_label(label_prefix, "imza en az uzunluk"),
            source_id=source,
            lane=lane,
            pointer=("sig", "minLength"),
            severity=Severity.CRITICAL,
            compare=Compare.NUMBER,
            expected=SIGNATURE_CHARS,
            rationale=(
                "Alt sinir kalibi tamamlar. Kaybolursa sema kisa bir imzayi "
                "yalniz kalip sayesinde reddediyor olur."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signature_max_length",
            label=_label(label_prefix, "imza en fazla uzunluk"),
            source_id=source,
            lane=lane,
            pointer=("sig", "maxLength"),
            severity=Severity.CRITICAL,
            compare=Compare.NUMBER,
            expected=SIGNATURE_CHARS,
            rationale="64 baytlik Ed25519 imzasinin padding'siz base64url uzunlugu.",
        ),
        ProtocolField(
            key=f"{prefix}nonce_type",
            label=_label(label_prefix, "nonce alan tipi"),
            source_id=source,
            lane=lane,
            pointer=("nonce", "type"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected="string",
            rationale=(
                "Nonce canonical string'e string olarak girer. Sayiya donerse "
                "imzalanan baytlar degisir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}nonce_pattern",
            label=_label(label_prefix, "nonce bicimi"),
            source_id=source,
            lane=lane,
            pointer=("nonce", "pattern"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected=EXPECTED_NONCE_PATTERN,
            rationale=(
                "Nonce canonical string'in icindedir, yani imza onu kapsar. "
                "Kalip degisirse imzalanan baytlar degisir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signed_fields_required",
            label=_label(label_prefix, "zorunlu imza alanlari"),
            source_id=source,
            lane=lane,
            pointer=(),
            severity=Severity.CRITICAL,
            compare=Compare.NAME_SET,
            expected=("nonce", "sig"),
            rationale=(
                "DID tasiyan bir govdede sig ve nonce zorunlu olmali. Bu iki "
                "adin yalnizca properties altinda gorunmesi zorunlu olduklarini "
                "kanitlamaz; kosullu required kaybolursa sunucu eksik "
                "kimlik bilgisiyle gelen bir govdeyi imzali saymayabilir."
            ),
            derived=Derived.SIGNED_REQUIRED,
        ),
    )


def _did_fields(
    lane: Lane, prefix: str, label_prefix: str
) -> tuple[ProtocolField, ...]:
    """``did`` sits on ``properties`` unconditionally, on both lanes."""
    return (
        ProtocolField(
            key=f"{prefix}did_pattern",
            label=_label(label_prefix, "DID bicimi"),
            source_id=SourceId.OPENAPI,
            lane=lane,
            pointer=("properties", "did", "pattern"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected=EXPECTED_DID_PATTERN,
            rationale=(
                "Sunucunun kabul ettigi DID kalibi. Degisirse Station'in "
                "urettigi did:key artik gecerli sayilmayabilir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}did_max_length",
            label=_label(label_prefix, "DID uzunlugu"),
            source_id=SourceId.OPENAPI,
            lane=lane,
            pointer=("properties", "did", "maxLength"),
            severity=Severity.CRITICAL,
            compare=Compare.NUMBER,
            expected=EXPECTED_DID_CHARS,
            rationale=(
                "Ed25519 did:key tam 56 karakterdir; farkli bir uzunluk farkli "
                "bir sema demektir."
            ),
        ),
    )


PROTOCOL_FIELDS: tuple[ProtocolField, ...] = (
    # --- the signed lanes exist at the method and path we will use ---------
    ProtocolField(
        key="signed_message_lane",
        label="Imzali mesaj yolu",
        source_id=SourceId.OPENAPI,
        lane=Lane.MESSAGE_BODY,
        pointer=(),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="POST /r/{room}",
        rationale=(
            "Station imzali mesaji bu method ve yola gonderecek. Yol veya "
            "method degisirse imza dogru uretilse bile istek yanlis yere gider."
        ),
        derived=Derived.LANE_PRESENT,
    ),
    ProtocolField(
        key="signed_note_lane",
        label="Imzali note yolu",
        source_id=SourceId.OPENAPI,
        lane=Lane.NOTE_BODY,
        pointer=(),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="POST /kv/{ns}/{key}",
        rationale=(
            "Imzali note yolu. Mesajla ayni gerekce: kaybolursa veya tasinirsa "
            "Station'in planladigi lane artik yok demektir."
        ),
        derived=Derived.LANE_PRESENT,
    ),
    # --- what the server enforces on a signed write, on both lanes ---------
    *_did_fields(Lane.MESSAGE_BODY, "", ""),
    *_signed_lane_fields(Lane.MESSAGE_SIGNED, "", ""),
    *_did_fields(Lane.NOTE_BODY, "note_", "Note "),
    *_signed_lane_fields(Lane.NOTE_SIGNED, "note_", "Note "),
    # --- the canonical strings a signature covers --------------------------
    ProtocolField(
        key="message_signature_payload",
        label="Mesaj canonical bicimi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "message_signature_payload"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="<room>|<nonce>|<text>",
        rationale=(
            "Imzanin kapsadigi tam bayt dizisi. Alan sirasi veya ayrac "
            "degisirse Station'in imzaladigi sey sunucunun bekledigi sey olmaz."
        ),
    ),
    ProtocolField(
        key="note_signature_payload",
        label="Note canonical bicimi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "note_signature_payload"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="<namespace>|<key>|<nonce>|<value>",
        rationale="Note imzasinin kapsadigi tam bayt dizisi.",
    ),
    ProtocolField(
        key="signature_encoding",
        label="Imza kodlamasi aciklamasi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "signature_encoding"),
        severity=Severity.CRITICAL,
        compare=Compare.PROSE,
        expected="base64url 86 unpadded",
        rationale=(
            "Kodlama sozlesmesinin insan tarafi. Asil dayanak makine "
            "semasidir - imza kalibi ve min/max uzunluk; bu alan onu "
            "dogrular. Ifade yeniden yazilabilir, fakat sozlesmeyi reddeden "
            "bir cumle yalniz dogru kelimeleri tasidigi icin gecmemelidir."
        ),
    ),
    ProtocolField(
        key="identity_scheme",
        label="Kimlik semasi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "scheme"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="did:key",
        rationale=(
            "Station yalniz did:key uretir; baska bir sema desteklenmiyor "
            "demektir."
        ),
    ),
    ProtocolField(
        key="identity_algorithm",
        label="Imza algoritmasi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "algorithms"),
        severity=Severity.CRITICAL,
        compare=Compare.MEMBER,
        expected="Ed25519",
        rationale=(
            "Station yalniz Ed25519 imzalar. Listeden cikarsa imzalarimiz "
            "gecersizdir."
        ),
    ),
    ProtocolField(
        key="name_pattern",
        label="Oda/namespace/key kalibi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("conventions", "name_pattern"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected=EXPECTED_NAME_PATTERN,
        rationale=(
            "Bu allow-list canonical string'i kacislama olmadan birlestirmeyi "
            "guvenli kilan seydir: yapisal alan asla '|' iceremez."
        ),
    ),
    # --- payload capacity from the body schema: warning + effective limit ---
    #
    # The charter (14.4) is explicit: a limit or capacity change produces a
    # warning, never a closed gate, and limits are read at runtime rather
    # than hard-coded. So a published payload bound is surfaced here as a
    # warning when it differs from the pinned contract, and the *effective*
    # bounds (see ProjectionResult.effective_payload_limits) are what the
    # composer enforces on the real request. Degenerate publications - an
    # empty range, or a schema that admits no payload at all - are caught
    # earlier by the evaluator and do close the gate.
    ProtocolField(
        key="payload_min_length",
        label="Mesaj en az uzunluk",
        source_id=SourceId.OPENAPI,
        lane=Lane.MESSAGE_BODY,
        pointer=("minLength",),
        severity=Severity.WARNING,
        compare=Compare.NUMBER,
        expected=1,
        rationale=(
            "Sunucunun mesaj metni icin yayimladigi alt sinir. Degisirse "
            "imza gecerliligi etkilenmez; composer istegi bu sinira gore "
            "denetler (kunye 14.4)."
        ),
        derived=Derived.PAYLOAD_BOUND,
    ),
    ProtocolField(
        key="payload_max_length",
        label="Mesaj en fazla uzunluk",
        source_id=SourceId.OPENAPI,
        lane=Lane.MESSAGE_BODY,
        pointer=("maxLength",),
        severity=Severity.WARNING,
        compare=Compare.NUMBER,
        expected=MAX_MESSAGE_CHARS,
        rationale=(
            "Sunucunun mesaj metni icin yayimladigi ust sinir. Kapasite "
            "degisikligi uyaridir; etkin limit composer'da uygulanir."
        ),
        derived=Derived.PAYLOAD_BOUND,
    ),
    ProtocolField(
        key="note_payload_min_length",
        label="Note en az uzunluk",
        source_id=SourceId.OPENAPI,
        lane=Lane.NOTE_BODY,
        pointer=("minLength",),
        severity=Severity.WARNING,
        compare=Compare.NUMBER,
        expected=1,
        rationale="Mesaj alt siniri ile ayni gerekce, note lane'i icin.",
        derived=Derived.PAYLOAD_BOUND,
    ),
    ProtocolField(
        key="note_payload_max_length",
        label="Note en fazla uzunluk",
        source_id=SourceId.OPENAPI,
        lane=Lane.NOTE_BODY,
        pointer=("maxLength",),
        severity=Severity.WARNING,
        compare=Compare.NUMBER,
        expected=MAX_NOTE_VALUE_CHARS,
        rationale="Mesaj ust siniri ile ayni gerekce, note lane'i icin.",
        derived=Derived.PAYLOAD_BOUND,
    ),
    # --- capacity and version: real changes, but a signature stays valid ----
    ProtocolField(
        key="message_chars",
        label="Mesaj karakter siniri",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("limits", "message_chars"),
        severity=Severity.WARNING,
        compare=Compare.NUMBER,
        expected=MAX_MESSAGE_CHARS,
        rationale=(
            "Kapasite degisikligi imzayi gecersiz kilmaz; kullanicinin gormesi "
            "gereken bir farktir (kunye 14.4)."
        ),
    ),
    ProtocolField(
        key="note_chars",
        label="Note karakter siniri",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("limits", "note_chars"),
        severity=Severity.WARNING,
        compare=Compare.NUMBER,
        expected=MAX_NOTE_VALUE_CHARS,
        rationale="Mesaj siniriyla ayni gerekce.",
    ),
    ProtocolField(
        key="service_version",
        label="Servis surumu",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("version",),
        severity=Severity.WARNING,
        compare=Compare.TEXT,
        expected=PINNED_SERVICE_VERSION,
        rationale=(
            "Pinlenmis referansin surumu. Daha yeni bir servis tek basina "
            "drift degildir - kritik alanlar ayrica denetlenir - fakat "
            "gorulmesi gereken bir farktir."
        ),
    ),
)


@dataclass(frozen=True, slots=True)
class FieldObservation:
    """The verdict for one field."""

    field: ProtocolField
    observed: str
    outcome: FieldOutcome
    #: Set when the outcome is ``UNSUPPORTED``; explains what was not read.
    problem: str = ""
    #: The original typed value for NUMBER-compared fields, so consumers (the
    #: effective payload limits below) never parse a display string back.
    raw: object = None

    @property
    def matches(self) -> bool:
        return self.outcome is FieldOutcome.MATCHED

    @property
    def is_critical_failure(self) -> bool:
        return not self.matches and self.field.severity is Severity.CRITICAL

    @property
    def is_critical_mismatch(self) -> bool:
        """A critical field that is present and genuinely different."""
        return (
            self.outcome is FieldOutcome.MISMATCH
            and self.field.severity is Severity.CRITICAL
        )

    @property
    def is_critical_unevaluable(self) -> bool:
        """A critical field we could not read. Not evidence of a change."""
        return (
            self.outcome in (FieldOutcome.MISSING, FieldOutcome.UNSUPPORTED)
            and self.field.severity is Severity.CRITICAL
        )

    @property
    def reason(self) -> str:
        """One line saying what happened, without overclaiming."""
        label = self.field.label
        if self.outcome is FieldOutcome.MISMATCH:
            if self.problem:
                return f"{label}: {self.problem}"
            return (
                f"{label}: beklenen {self.field.expected_display!r}, "
                f"gorulen {self.observed!r}"
            )
        if self.outcome is FieldOutcome.MISSING:
            return (
                f"{label}: belgede bulunamadi ({self.field.json_path}); "
                "protokol uyumu dogrulanamadi"
            )
        if self.outcome is FieldOutcome.UNSUPPORTED:
            return (
                f"{label}: sema bicimi okunamadi ({self.problem}); "
                "protokol uyumu dogrulanamadi"
            )
        return ""


@dataclass(frozen=True, slots=True)
class ProjectionResult:
    """The outcome of comparing the live documents with the expectation."""

    state: DriftState
    observations: tuple[FieldObservation, ...]
    #: Human-readable reasons the state is not ``current``.
    reasons: tuple[str, ...]

    @property
    def critical_mismatches(self) -> tuple[FieldObservation, ...]:
        """Critical fields that are present and different: real drift."""
        return tuple(item for item in self.observations if item.is_critical_mismatch)

    @property
    def critical_unevaluable(self) -> tuple[FieldObservation, ...]:
        """Critical fields that could not be read at all."""
        return tuple(item for item in self.observations if item.is_critical_unevaluable)

    @property
    def critical_failures(self) -> tuple[FieldObservation, ...]:
        """Every critical field that did not match, whatever the reason."""
        return tuple(item for item in self.observations if item.is_critical_failure)

    @property
    def effective_payload_limits(self) -> dict[str, SentLength]:
        """What the composer must enforce per payload field, from live data.

        The published bounds (or the pinned expectation where none was
        published) intersected with our own contract: never below one visible
        character, never above the charter maximum. Keys are the payload
        field names (``text``, ``value``). Only meaningful when the check
        completed; on an unavailable/drifted verdict the gate is shut anyway.
        """
        bounds: dict[str, dict[str, int]] = {}
        keyed = {
            "payload_min_length": ("text", "low"),
            "payload_max_length": ("text", "high"),
            "note_payload_min_length": ("value", "low"),
            "note_payload_max_length": ("value", "high"),
        }
        for item in self.observations:
            slot = keyed.get(item.field.key)
            if slot is None:
                continue
            name, side = slot
            value = item.raw if isinstance(item.raw, int) else item.field.expected
            if isinstance(value, int):
                bounds.setdefault(name, {})[side] = value
        ceilings = {"text": MAX_MESSAGE_CHARS, "value": MAX_NOTE_VALUE_CHARS}
        return {
            name: SentLength(
                max(1, sides.get("low", 1)),
                min(sides.get("high", ceilings[name]), ceilings[name]),
            )
            for name, sides in bounds.items()
        }

    @property
    def warnings(self) -> tuple[FieldObservation, ...]:
        return tuple(
            item
            for item in self.observations
            if not item.matches and item.field.severity is Severity.WARNING
        )


# ---------------------------------------------------------------------------
# Display and comparison
# ---------------------------------------------------------------------------


def sweep_untrusted(text: str) -> str:
    """Replace invisible characters with a space. No truncation.

    Used before *scanning* a remote description, where a marker hiding past a
    display limit would matter. Display uses :func:`safe_display`.
    """
    return "".join(
        " " if unicodedata.category(character) in _INVISIBLE else character
        for character in text
    )


def safe_display(value: object) -> str:
    """Make a remote value safe to store, log and render.

    Control, format and separator characters become a space, and the result is
    truncated. Level-1 authority means the document is probably accurate; it
    does not mean the bytes are safe to paste into a log line or a UI.

    This is a **display** function. Nothing compares its output: sweeping and
    stripping would make a payload with a trailing newline equal to the
    canonical one, and it is not.
    """
    if isinstance(value, _Absent):
        return MISSING
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    text = (
        ",".join(safe_display(item) for item in value)
        if isinstance(value, list)
        else str(value)
    )

    swept = sweep_untrusted(text).strip()
    if len(swept) > MAX_OBSERVED_CHARS:
        return swept[:MAX_OBSERVED_CHARS] + "..."
    return swept


def _prose_matches(value: str, expected: str) -> bool:
    """Every machine token present as a word, and no negation anywhere."""
    lowered = sweep_untrusted(value).lower()
    if any(
        re.search(rf"\b{re.escape(marker)}\b", lowered) for marker in NEGATION_MARKERS
    ):
        return False
    return all(
        re.search(rf"\b{re.escape(token)}\b", lowered) for token in expected.split()
    )


def _compare(field: ProtocolField, value: object) -> bool:
    """Type-checked comparison against the original value."""
    expected = field.expected

    if field.compare is Compare.TEXT:
        return isinstance(value, str) and value == expected
    if field.compare is Compare.NUMBER:
        # bool is an int subclass and True == 1; a published `true` is not 1.
        return (
            isinstance(value, int) and not isinstance(value, bool) and value == expected
        )
    if field.compare is Compare.MEMBER:
        return isinstance(value, list) and any(
            isinstance(item, str) and item == expected for item in value
        )
    if field.compare is Compare.NAME_SET:
        if not isinstance(value, list) or not all(
            isinstance(item, str) for item in value
        ):
            return False
        return isinstance(expected, tuple) and set(value) == set(expected)
    if field.compare is Compare.PROSE:
        return (
            isinstance(value, str)
            and isinstance(expected, str)
            and _prose_matches(value, expected)
        )
    # Exhaustive. A new comparison mode fails type-checking here rather than
    # silently defaulting to "matches" or "does not match".
    assert_never(field.compare)


# ---------------------------------------------------------------------------
# Extraction
# ---------------------------------------------------------------------------


def _lane_root(field: ProtocolField, document: dict[str, Any]) -> Reading:
    """The node a field's pointer is relative to.

    Every lane field - the unconditional ones as much as the conditional ones -
    goes through :func:`evaluate_signed_body` first. A body whose combined
    meaning cannot be read, or which contradicts itself, must not hand out a
    correct-looking pattern from one corner of itself: reading the right value
    out of a schema that rejects every signed request is exactly the failure
    this evaluation exists to prevent.
    """
    if field.lane is Lane.DOCUMENT:
        return Reading(value=document)

    body = read_pointer(document, _LANE_POINTERS[field.lane])
    if isinstance(body, _Absent):
        return Reading()

    evaluated = evaluate_signed_body(body, PLANNED_BODY_FIELDS[field.lane])
    if evaluated.problem or evaluated.conflict:
        return evaluated
    view = evaluated.value
    if not isinstance(view, SignedBodyView):  # pragma: no cover - guaranteed
        return Reading(problem="imzali lane okunamadi")

    if field.derived is Derived.PAYLOAD_BOUND:
        return Reading(value=view)
    if field.lane not in (Lane.MESSAGE_SIGNED, Lane.NOTE_SIGNED):
        return Reading(value=view.body)
    if field.derived is Derived.SIGNED_REQUIRED:
        return Reading(value=view.lane)
    return Reading(value=view.credentials)


def _read(field: ProtocolField, document: dict[str, Any]) -> Reading:
    """Read the value a field describes, including the derived ones."""
    root = _lane_root(field, document)
    if root.problem or root.conflict or isinstance(root.value, _Absent):
        return root

    if field.derived is Derived.PAYLOAD_BOUND:
        view = root.value
        if not isinstance(view, SignedBodyView):  # pragma: no cover - guaranteed
            return Reading(problem="imzali lane okunamadi")
        bound = (
            view.payload_low if field.pointer == ("minLength",) else view.payload_high
        )
        # An unpublished bound constrains nothing, so it observes as the
        # expectation itself: only a real published change produces a warning.
        return Reading(value=field.expected if bound is None else bound)

    if field.derived is Derived.LANE_PRESENT:
        return Reading(value=field.expected if isinstance(root.value, dict) else ABSENT)

    if field.derived is Derived.SIGNED_REQUIRED:
        node = root.value
        if not isinstance(node, dict):  # pragma: no cover - guaranteed above
            return Reading()
        required = node.get("required")
        return Reading() if required is None else Reading(value=required)

    value = read_pointer(root.value, field.pointer)
    if (
        field.compare is Compare.PROSE
        and isinstance(value, str)
        and len(sweep_untrusted(value)) > MAX_PROSE_CHARS
    ):
        return Reading(problem="aciklama beklenenden cok uzun, degerlendirilmedi")
    return Reading(value=value)


def _observe(
    field: ProtocolField, documents: dict[SourceId, dict[str, Any]]
) -> FieldObservation:
    document = documents.get(field.source_id)
    if document is None:
        return FieldObservation(
            field=field, observed=MISSING, outcome=FieldOutcome.MISSING
        )

    reading = _read(field, document)
    if reading.conflict:
        # Evaluated, and impossible to satisfy. That is a real statement about
        # the document, so it is reported as a difference rather than as
        # "could not check".
        return FieldObservation(
            field=field,
            observed=safe_display(reading.value),
            outcome=FieldOutcome.MISMATCH,
            problem=reading.conflict,
        )
    if reading.problem:
        return FieldObservation(
            field=field,
            observed=safe_display(reading.value),
            outcome=FieldOutcome.UNSUPPORTED,
            problem=reading.problem,
        )
    if isinstance(reading.value, _Absent):
        return FieldObservation(
            field=field, observed=MISSING, outcome=FieldOutcome.MISSING
        )

    outcome = (
        FieldOutcome.MATCHED if _compare(field, reading.value) else FieldOutcome.MISMATCH
    )
    return FieldObservation(
        field=field,
        observed=safe_display(reading.value),
        outcome=outcome,
        raw=reading.value if field.compare is Compare.NUMBER else None,
    )


def project(documents: dict[SourceId, dict[str, Any]]) -> ProjectionResult:
    """Compare the live documents with the expected contract.

    ``documents`` holds only the sources that parsed. Three outcomes:

    * a critical field present and different is **drift**;
    * a critical field that could not be read is **unavailable** - the check
      did not complete, and saying more than that would be a claim about the
      server that the evidence does not support;
    * otherwise **current**, with any warnings listed beside it.

    Drift wins over unavailable: a real, readable change is the more specific
    answer and the more useful one. Either way ``manifest_current`` is false.
    """
    observations = tuple(_observe(field, documents) for field in PROTOCOL_FIELDS)

    mismatches = [item for item in observations if item.is_critical_mismatch]
    if mismatches:
        return ProjectionResult(
            state=DriftState.DRIFTED,
            observations=observations,
            reasons=tuple(item.reason for item in mismatches),
        )

    unevaluable = [item for item in observations if item.is_critical_unevaluable]
    if unevaluable:
        return ProjectionResult(
            state=DriftState.UNAVAILABLE,
            observations=observations,
            reasons=tuple(item.reason for item in unevaluable),
        )

    return ProjectionResult(
        state=DriftState.CURRENT, observations=observations, reasons=()
    )


def unavailable(reasons: tuple[str, ...]) -> ProjectionResult:
    """A verdict for a check that could not be completed."""
    return ProjectionResult(
        state=DriftState.UNAVAILABLE, observations=(), reasons=reasons
    )


__all__ = [
    "ABSENT",
    "ANNOTATION_KEYS",
    "EXPECTED_DID_CHARS",
    "EXPECTED_DID_PATTERN",
    "EXPECTED_NAME_PATTERN",
    "EXPECTED_NONCE_PATTERN",
    "EXPECTED_SIGNATURE_PATTERN",
    "MAX_OBSERVED_CHARS",
    "MAX_PATTERN_CHARS",
    "MAX_PROSE_CHARS",
    "MESSAGE_BODY_POINTER",
    "MISSING",
    "NEGATION_MARKERS",
    "NONCE_MAX_DIGITS",
    "NONCE_MIN_DIGITS",
    "NOTE_BODY_POINTER",
    "PINNED_SERVICE_VERSION",
    "PLANNED_BODY_FIELDS",
    "PROTOCOL_FIELDS",
    "STATION_FIELD_LENGTHS",
    "UNDERSTOOD_BODY_KEYS",
    "UNDERSTOOD_BRANCH_KEYS",
    "UNDERSTOOD_FIELD_KEYS",
    "UNDERSTOOD_LANE_KEYS",
    "Compare",
    "Derived",
    "DriftState",
    "FieldObservation",
    "FieldOutcome",
    "Lane",
    "ProjectionResult",
    "ProtocolField",
    "Reading",
    "SentLength",
    "Severity",
    "SignedBodyView",
    "evaluate_signed_body",
    "pointer_text",
    "project",
    "read_pointer",
    "safe_display",
    "sweep_untrusted",
    "unavailable",
]
