"""The critical protocol projection, and drift against it.

A raw hash of ``/openapi.json`` would flag every typo fix as protocol drift
and would therefore be ignored within a week. What matters is narrower: the
handful of machine-readable facts a signature's validity depends on. This
module names them, states where each one lives, says why it is critical, and
compares the live value against what Station signs for.

Where the signed lane actually lives
------------------------------------
The reference does **not** publish the ``sig`` and ``nonce`` constraints on
``schema.properties``. It hangs them off ``did``::

    schema.dependentSchemas.did = {
        "required": ["sig", "nonce"],
        "properties": {"sig": {...}, "nonce": {...}},
    }

and leaves ``properties.sig`` carrying nothing but a ``description``. The
reference explains why: a body with no ``did`` is an ordinary unsigned write,
and ``sig``/``nonce`` on one are ignored rather than validated, so publishing
their patterns unconditionally would document a constraint nothing enforces.

Stage 3 read them from ``properties`` and therefore found nothing, which is
the false "the server changed the signature format" alarm this module now
exists to not repeat. Every pointer below is verified against documents
generated by the pinned reference itself - see
``tests/security/technocore_reference/PROVENANCE.md``.

Being absent is not the same as being different
-----------------------------------------------
A field the document does not carry, and a schema shape this module does not
understand, are both reported as *unevaluable* rather than as drift. Both keep
the gate shut - the verdict is fail-closed either way - but the reason the
user reads is "protocol conformance could not be verified" rather than a claim
about what the server did. Stating "every signature will be rejected" on the
strength of a lookup that went to the wrong place is exactly the mistake that
made this module wrong the first time.

Expectations come from our own contract
---------------------------------------
The patterns are derived from :mod:`technocore_conform`, the engine that
actually signs. Copying them out of the live document would make the check
self-fulfilling: it would report "current" forever and detect nothing.

Remote values are untrusted input
---------------------------------
Authority level 1 buys accuracy, not safety. Every observed value is
truncated and stripped of control characters *for display*. The comparison
itself runs against the original, type-checked value, so a padded or
whitespace-decorated payload cannot be normalised into a match.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from enum import StrEnum
from typing import Any, Final, assert_never

from technocore_conform import (
    DID_KEY_PREFIX,
    MAX_MESSAGE_CHARS,
    MAX_NOTE_VALUE_CHARS,
    MULTIBASE_LENGTH,
    NAME_PATTERN,
    NONCE_PATTERN,
    SIGNATURE_CHARS,
    SIGNATURE_PATTERN,
)

from station_api.technocore.sources import SourceId

#: Longest observed value kept for display. Generous for a pattern, far too
#: small to be a useful smuggling channel.
MAX_OBSERVED_CHARS = 200

#: Longest prose value this module will even try to read. A description
#: beyond this is not judged - it is reported as unevaluable, because a
#: negation could be hiding past any bound we did scan.
MAX_PROSE_CHARS = 2000

#: Marker used when a document does not carry the field at all. Distinct from
#: an empty string, which would be a value the server actually published.
MISSING = "<yok>"

_INVISIBLE = frozenset({"Cc", "Cf", "Cs", "Co", "Zl", "Zp"})


class _Absent:
    """Sentinel for "the document does not carry this".

    A distinct object rather than ``None`` because ``null`` is a value a
    server can legitimately publish, and the two must not be confused.
    """

    __slots__ = ()

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return "<absent>"


ABSENT: Final = _Absent()


class DriftState(StrEnum):
    """The four states the manifest check can report."""

    #: No live check has run in this process. The starting state, every time.
    NEVER_CHECKED = "never_checked"
    #: Every critical field matches what Station signs for.
    CURRENT = "current"
    #: At least one critical field is present and differs. The gate closes.
    DRIFTED = "drifted"
    #: A required document could not be fetched or parsed, or a critical
    #: field could not be evaluated. The gate closes.
    UNAVAILABLE = "unavailable"


class Severity(StrEnum):
    CRITICAL = "critical"
    WARNING = "warning"


class FieldOutcome(StrEnum):
    """What happened to one field, distinguishing absence from difference."""

    MATCHED = "matched"
    #: Present, readable, and different. This is real drift.
    MISMATCH = "mismatch"
    #: The document does not carry the field at the documented pointer.
    MISSING = "missing"
    #: The document carries a schema shape this module cannot read safely.
    UNSUPPORTED = "unsupported"


class Compare(StrEnum):
    """How an observed value is judged against the expected one.

    Every mode is type-checked. ``"86"`` is not ``86``: a server that
    published the string would be publishing a different schema, and a
    comparison that stringified both would call them equal.
    """

    #: Exact string equality on the original value. No sweeping, no
    #: stripping: a trailing newline is a different canonical payload.
    TEXT = "text"
    #: Exact integer equality. ``bool`` is rejected explicitly - it is an
    #: ``int`` subclass, and ``True == 1``.
    NUMBER = "number"
    #: The expected string must appear in a JSON array of strings.
    MEMBER = "member"
    #: A JSON array of strings whose set equals the expected set. Used for
    #: conditional ``required``, where order carries no meaning.
    NAME_SET = "name_set"
    #: A bounded prose check: every machine token present, no negation
    #: marker anywhere. See :data:`NEGATION_MARKERS`.
    PROSE = "prose"


class Lane(StrEnum):
    """Which sub-document a field's pointer is relative to."""

    #: The document root.
    DOCUMENT = "document"
    #: The message POST request-body schema.
    MESSAGE_BODY = "message_body"
    #: The note POST request-body schema.
    NOTE_BODY = "note_body"
    #: The subschema that applies to a message body *once it carries a did*.
    MESSAGE_SIGNED = "message_signed"
    #: The same, for a note body.
    NOTE_SIGNED = "note_signed"


class Derived(StrEnum):
    """Fields computed from a lane rather than read at a pointer."""

    #: The lane exists at the method and path Station will use.
    LANE_PRESENT = "lane_present"
    #: The set of field names the signed lane makes *required*.
    SIGNED_REQUIRED = "signed_required"


# ---------------------------------------------------------------------------
# Reading a document
# ---------------------------------------------------------------------------

#: Explicit segments, never a dotted string. ``paths./r/{room}.post`` split on
#: dots is ambiguous, and resolving it by longest-key matching let a remote
#: document shadow the real location by publishing a literal key with dots in
#: it. Segments remove the ambiguity rather than guarding against it.
MESSAGE_BODY_POINTER: Final[tuple[str, ...]] = (
    "paths",
    "/r/{room}",
    "post",
    "requestBody",
    "content",
    "application/json",
    "schema",
)
NOTE_BODY_POINTER: Final[tuple[str, ...]] = (
    "paths",
    "/kv/{ns}/{key}",
    "post",
    "requestBody",
    "content",
    "application/json",
    "schema",
)

#: JSON Schema keywords that can redirect or negate what a subschema means.
#: If one appears where the signed lane is read, this module does not claim to
#: understand the document. ``anyOf`` is deliberately absent: the reference
#: publishes one (``from`` or ``did`` is required), and because keywords at a
#: level are conjunctive it can only add a constraint on top of
#: ``dependentSchemas`` - it cannot loosen it.
AMBIGUOUS_KEYWORDS: Final = frozenset(
    {"$ref", "$dynamicRef", "allOf", "oneOf", "not", "if"}
)

#: Words that deny a contract rather than restate it. A description is not
#: accepted merely because the right words appear in it: "86 characters, but
#: no longer unpadded" contains every token and means the opposite.
#:
#: The list is closed and short on purpose, and it is checked against the real
#: pinned description, which says "Re-encode the raw signature *rather than*
#: editing its tail" - so "rather than" is not a marker. Neither are "no" or
#: "without", because "no padding" is a legitimate way to say unpadded.
#: ``padded`` is matched on a word boundary, which "unpadded" does not create.
NEGATION_MARKERS: Final[tuple[str, ...]] = (
    "not",
    "never",
    "no longer",
    "instead",
    "deprecated",
    "obsolete",
    "removed",
    "padded",
)


def read_pointer(document: object, segments: tuple[str, ...]) -> object:
    """Walk explicit segments. Returns :data:`ABSENT` if any is missing."""
    current: object = document
    for segment in segments:
        if not isinstance(current, dict) or segment not in current:
            return ABSENT
        current = current[segment]
    return current


def pointer_text(segments: tuple[str, ...]) -> str:
    """The segments as a JSON Pointer, for display and for the record."""
    escaped = (segment.replace("~", "~0").replace("/", "~1") for segment in segments)
    return "/" + "/".join(escaped)


@dataclass(frozen=True, slots=True)
class Reading:
    """A value read from a document, or the reason it could not be."""

    value: object = ABSENT
    #: Non-empty when the shape could not be read safely.
    problem: str = ""


def resolve_signed_lane(schema: object) -> Reading:
    """The subschema that applies to a request body once it carries a ``did``.

    Returns the ``dependentSchemas.did`` node. Refuses - rather than guesses -
    when the surrounding schema uses a keyword that could change what that
    node means, so an upstream move to ``$ref`` or ``if``/``then`` is reported
    as "cannot verify" instead of silently passing or silently failing.
    """
    if not isinstance(schema, dict):
        return Reading(problem="istek govdesi semasi bir nesne degil")

    intrusive = sorted(AMBIGUOUS_KEYWORDS & set(schema))
    if intrusive:
        return Reading(problem=f"desteklenmeyen sema anahtari: {', '.join(intrusive)}")

    dependent = schema.get("dependentSchemas")
    if dependent is None:
        return Reading(problem="imzali lane kosullu semasi yok (dependentSchemas eksik)")
    if not isinstance(dependent, dict):
        return Reading(problem="dependentSchemas bir nesne degil")

    lane = dependent.get("did")
    if lane is None:
        return Reading(problem="dependentSchemas.did yok")
    if not isinstance(lane, dict):
        return Reading(problem="dependentSchemas.did bir nesne degil")

    nested = sorted(AMBIGUOUS_KEYWORDS & set(lane))
    if nested:
        return Reading(
            problem=f"dependentSchemas.did desteklenmeyen anahtar: {', '.join(nested)}"
        )

    if not isinstance(lane.get("properties"), dict):
        return Reading(problem="dependentSchemas.did.properties bir nesne degil")

    return Reading(value=lane)


# ---------------------------------------------------------------------------
# The expected contract
#
# Derived from technocore_conform, the engine that signs. Pinned here rather
# than read from the live service on purpose: a checker that adopted whatever
# the server currently says would report "current" forever.
# ---------------------------------------------------------------------------

#: ``did:key:z6Mk`` plus the remaining base58btc characters. The alphabet is
#: base58btc - the four ambiguous glyphs are absent - and the count follows
#: from the multibase length our own did module enforces.
EXPECTED_DID_PATTERN: Final = (
    rf"^{DID_KEY_PREFIX}z6Mk[1-9A-HJ-NP-Za-km-z]{{{MULTIBASE_LENGTH - 4}}}$"
)
EXPECTED_DID_CHARS: Final = len(DID_KEY_PREFIX) + MULTIBASE_LENGTH
EXPECTED_SIGNATURE_PATTERN: Final = f"^{SIGNATURE_PATTERN}$"
EXPECTED_NONCE_PATTERN: Final = f"^{NONCE_PATTERN}$"
EXPECTED_NAME_PATTERN: Final = f"^{NAME_PATTERN}$"

#: The version of the pinned reference this projection was built against. A
#: newer service is a warning, never drift: the protocol facts above are what
#: decide whether a signature stays valid.
PINNED_SERVICE_VERSION: Final = "0.10.0"


@dataclass(frozen=True, slots=True)
class ProtocolField:
    """One fact the live service publishes, and what Station expects."""

    key: str
    label: str
    source_id: SourceId
    lane: Lane
    #: Segments relative to the lane root. Empty for a derived field.
    pointer: tuple[str, ...]
    severity: Severity
    compare: Compare
    expected: str | int | tuple[str, ...]
    #: Why a change here matters. Shown to the user, so it explains the
    #: consequence rather than restating the field name.
    rationale: str
    derived: Derived | None = None

    @property
    def json_path(self) -> str:
        """Where the value lives, as a JSON Pointer, for display."""
        root = _LANE_POINTERS[self.lane]
        if self.derived is Derived.SIGNED_REQUIRED:
            return pointer_text((*root, "dependentSchemas", "did", "required"))
        if self.derived is Derived.LANE_PRESENT:
            return pointer_text(root)
        if self.lane in (Lane.MESSAGE_SIGNED, Lane.NOTE_SIGNED):
            return pointer_text(
                (*root, "dependentSchemas", "did", "properties", *self.pointer)
            )
        return pointer_text((*root, *self.pointer))

    @property
    def expected_display(self) -> str:
        """The expectation as a string, for the API and the UI."""
        if isinstance(self.expected, tuple):
            return ", ".join(self.expected)
        return str(self.expected)


_LANE_POINTERS: Final[dict[Lane, tuple[str, ...]]] = {
    Lane.DOCUMENT: (),
    Lane.MESSAGE_BODY: MESSAGE_BODY_POINTER,
    Lane.NOTE_BODY: NOTE_BODY_POINTER,
    Lane.MESSAGE_SIGNED: MESSAGE_BODY_POINTER,
    Lane.NOTE_SIGNED: NOTE_BODY_POINTER,
}


def _label(prefix: str, base: str) -> str:
    """``"Note imza bicimi"`` for the note lane, ``"Imza bicimi"`` for the other.

    The lane prefix carries the capital when there is one, so the base text is
    written lowercase and capitalised only when it starts the label.
    """
    return f"{prefix}{base}" if prefix else base[0].upper() + base[1:]


def _signed_lane_fields(
    lane: Lane, prefix: str, label_prefix: str
) -> tuple[ProtocolField, ...]:
    """The constraints a signed lane must publish, for one lane.

    Written once and used for both lanes: the note lane drifting away from the
    message lane is itself a protocol change, and a copy-pasted block is how
    one of them silently stops being checked.
    """
    source = SourceId.OPENAPI
    return (
        ProtocolField(
            key=f"{prefix}signature_type",
            label=_label(label_prefix, "imza alan tipi"),
            source_id=source,
            lane=lane,
            pointer=("sig", "type"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected="string",
            rationale=(
                "Imza alani string olarak tanimli olmali. Tip degisirse sunucu "
                "imzayi bizim urettigimiz bicimde okumuyor demektir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signature_pattern",
            label=_label(label_prefix, "imza bicimi"),
            source_id=source,
            lane=lane,
            pointer=("sig", "pattern"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected=EXPECTED_SIGNATURE_PATTERN,
            rationale=(
                "Padding'siz base64url, 86 karakter, son karakter AQgw'den "
                "biri (AC-04). 64 baytlik imzanin son karakterinde dort bos "
                "bit kalir; daha genis bir kalip bu bitleri sifir olmayan "
                "imzalari da kabul eder ve sozlesmeyi oldugundan gevsek "
                "gosterir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signature_min_length",
            label=_label(label_prefix, "imza en az uzunluk"),
            source_id=source,
            lane=lane,
            pointer=("sig", "minLength"),
            severity=Severity.CRITICAL,
            compare=Compare.NUMBER,
            expected=SIGNATURE_CHARS,
            rationale=(
                "Alt sinir kalibi tamamlar. Kaybolursa sema kisa bir imzayi "
                "yalniz kalip sayesinde reddediyor olur."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signature_max_length",
            label=_label(label_prefix, "imza en fazla uzunluk"),
            source_id=source,
            lane=lane,
            pointer=("sig", "maxLength"),
            severity=Severity.CRITICAL,
            compare=Compare.NUMBER,
            expected=SIGNATURE_CHARS,
            rationale="64 baytlik Ed25519 imzasinin padding'siz base64url uzunlugu.",
        ),
        ProtocolField(
            key=f"{prefix}nonce_type",
            label=_label(label_prefix, "nonce alan tipi"),
            source_id=source,
            lane=lane,
            pointer=("nonce", "type"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected="string",
            rationale=(
                "Nonce canonical string'e string olarak girer. Sayiya donerse "
                "imzalanan baytlar degisir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}nonce_pattern",
            label=_label(label_prefix, "nonce bicimi"),
            source_id=source,
            lane=lane,
            pointer=("nonce", "pattern"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected=EXPECTED_NONCE_PATTERN,
            rationale=(
                "Nonce canonical string'in icindedir, yani imza onu kapsar. "
                "Kalip degisirse imzalanan baytlar degisir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}signed_fields_required",
            label=_label(label_prefix, "zorunlu imza alanlari"),
            source_id=source,
            lane=lane,
            pointer=(),
            severity=Severity.CRITICAL,
            compare=Compare.NAME_SET,
            expected=("nonce", "sig"),
            rationale=(
                "DID tasiyan bir govdede sig ve nonce zorunlu olmali. Bu iki "
                "adin yalnizca properties altinda gorunmesi zorunlu olduklarini "
                "kanitlamaz; kosullu required kaybolursa sunucu eksik "
                "kimlik bilgisiyle gelen bir govdeyi imzali saymayabilir."
            ),
            derived=Derived.SIGNED_REQUIRED,
        ),
    )


def _did_fields(
    lane: Lane, prefix: str, label_prefix: str
) -> tuple[ProtocolField, ...]:
    """``did`` sits on ``properties`` unconditionally, on both lanes."""
    return (
        ProtocolField(
            key=f"{prefix}did_pattern",
            label=_label(label_prefix, "DID bicimi"),
            source_id=SourceId.OPENAPI,
            lane=lane,
            pointer=("properties", "did", "pattern"),
            severity=Severity.CRITICAL,
            compare=Compare.TEXT,
            expected=EXPECTED_DID_PATTERN,
            rationale=(
                "Sunucunun kabul ettigi DID kalibi. Degisirse Station'in "
                "urettigi did:key artik gecerli sayilmayabilir."
            ),
        ),
        ProtocolField(
            key=f"{prefix}did_max_length",
            label=_label(label_prefix, "DID uzunlugu"),
            source_id=SourceId.OPENAPI,
            lane=lane,
            pointer=("properties", "did", "maxLength"),
            severity=Severity.CRITICAL,
            compare=Compare.NUMBER,
            expected=EXPECTED_DID_CHARS,
            rationale=(
                "Ed25519 did:key tam 56 karakterdir; farkli bir uzunluk farkli "
                "bir sema demektir."
            ),
        ),
    )


PROTOCOL_FIELDS: tuple[ProtocolField, ...] = (
    # --- the signed lanes exist at the method and path we will use ---------
    ProtocolField(
        key="signed_message_lane",
        label="Imzali mesaj yolu",
        source_id=SourceId.OPENAPI,
        lane=Lane.MESSAGE_BODY,
        pointer=(),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="POST /r/{room}",
        rationale=(
            "Station imzali mesaji bu method ve yola gonderecek. Yol veya "
            "method degisirse imza dogru uretilse bile istek yanlis yere gider."
        ),
        derived=Derived.LANE_PRESENT,
    ),
    ProtocolField(
        key="signed_note_lane",
        label="Imzali note yolu",
        source_id=SourceId.OPENAPI,
        lane=Lane.NOTE_BODY,
        pointer=(),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="POST /kv/{ns}/{key}",
        rationale=(
            "Imzali note yolu. Mesajla ayni gerekce: kaybolursa veya tasinirsa "
            "Station'in planladigi lane artik yok demektir."
        ),
        derived=Derived.LANE_PRESENT,
    ),
    # --- what the server enforces on a signed write, on both lanes ---------
    *_did_fields(Lane.MESSAGE_BODY, "", ""),
    *_signed_lane_fields(Lane.MESSAGE_SIGNED, "", ""),
    *_did_fields(Lane.NOTE_BODY, "note_", "Note "),
    *_signed_lane_fields(Lane.NOTE_SIGNED, "note_", "Note "),
    # --- the canonical strings a signature covers --------------------------
    ProtocolField(
        key="message_signature_payload",
        label="Mesaj canonical bicimi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "message_signature_payload"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="<room>|<nonce>|<text>",
        rationale=(
            "Imzanin kapsadigi tam bayt dizisi. Alan sirasi veya ayrac "
            "degisirse Station'in imzaladigi sey sunucunun bekledigi sey olmaz."
        ),
    ),
    ProtocolField(
        key="note_signature_payload",
        label="Note canonical bicimi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "note_signature_payload"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="<namespace>|<key>|<nonce>|<value>",
        rationale="Note imzasinin kapsadigi tam bayt dizisi.",
    ),
    ProtocolField(
        key="signature_encoding",
        label="Imza kodlamasi aciklamasi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "signature_encoding"),
        severity=Severity.CRITICAL,
        compare=Compare.PROSE,
        expected="base64url 86 unpadded",
        rationale=(
            "Kodlama sozlesmesinin insan tarafi. Asil dayanak makine "
            "semasidir - imza kalibi ve min/max uzunluk; bu alan onu "
            "dogrular. Ifade yeniden yazilabilir, fakat sozlesmeyi reddeden "
            "bir cumle yalniz dogru kelimeleri tasidigi icin gecmemelidir."
        ),
    ),
    ProtocolField(
        key="identity_scheme",
        label="Kimlik semasi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "scheme"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected="did:key",
        rationale=(
            "Station yalniz did:key uretir; baska bir sema desteklenmiyor "
            "demektir."
        ),
    ),
    ProtocolField(
        key="identity_algorithm",
        label="Imza algoritmasi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("identity", "algorithms"),
        severity=Severity.CRITICAL,
        compare=Compare.MEMBER,
        expected="Ed25519",
        rationale=(
            "Station yalniz Ed25519 imzalar. Listeden cikarsa imzalarimiz "
            "gecersizdir."
        ),
    ),
    ProtocolField(
        key="name_pattern",
        label="Oda/namespace/key kalibi",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("conventions", "name_pattern"),
        severity=Severity.CRITICAL,
        compare=Compare.TEXT,
        expected=EXPECTED_NAME_PATTERN,
        rationale=(
            "Bu allow-list canonical string'i kacislama olmadan birlestirmeyi "
            "guvenli kilan seydir: yapisal alan asla '|' iceremez."
        ),
    ),
    # --- capacity and version: real changes, but a signature stays valid ----
    ProtocolField(
        key="message_chars",
        label="Mesaj karakter siniri",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("limits", "message_chars"),
        severity=Severity.WARNING,
        compare=Compare.NUMBER,
        expected=MAX_MESSAGE_CHARS,
        rationale=(
            "Kapasite degisikligi imzayi gecersiz kilmaz; kullanicinin gormesi "
            "gereken bir farktir (kunye 14.4)."
        ),
    ),
    ProtocolField(
        key="note_chars",
        label="Note karakter siniri",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("limits", "note_chars"),
        severity=Severity.WARNING,
        compare=Compare.NUMBER,
        expected=MAX_NOTE_VALUE_CHARS,
        rationale="Mesaj siniriyla ayni gerekce.",
    ),
    ProtocolField(
        key="service_version",
        label="Servis surumu",
        source_id=SourceId.AGENT_MANIFEST,
        lane=Lane.DOCUMENT,
        pointer=("version",),
        severity=Severity.WARNING,
        compare=Compare.TEXT,
        expected=PINNED_SERVICE_VERSION,
        rationale=(
            "Pinlenmis referansin surumu. Daha yeni bir servis tek basina "
            "drift degildir - kritik alanlar ayrica denetlenir - fakat "
            "gorulmesi gereken bir farktir."
        ),
    ),
)


@dataclass(frozen=True, slots=True)
class FieldObservation:
    """The verdict for one field."""

    field: ProtocolField
    observed: str
    outcome: FieldOutcome
    #: Set when the outcome is ``UNSUPPORTED``; explains what was not read.
    problem: str = ""

    @property
    def matches(self) -> bool:
        return self.outcome is FieldOutcome.MATCHED

    @property
    def is_critical_failure(self) -> bool:
        return not self.matches and self.field.severity is Severity.CRITICAL

    @property
    def is_critical_mismatch(self) -> bool:
        """A critical field that is present and genuinely different."""
        return (
            self.outcome is FieldOutcome.MISMATCH
            and self.field.severity is Severity.CRITICAL
        )

    @property
    def is_critical_unevaluable(self) -> bool:
        """A critical field we could not read. Not evidence of a change."""
        return (
            self.outcome in (FieldOutcome.MISSING, FieldOutcome.UNSUPPORTED)
            and self.field.severity is Severity.CRITICAL
        )

    @property
    def reason(self) -> str:
        """One line saying what happened, without overclaiming."""
        label = self.field.label
        if self.outcome is FieldOutcome.MISMATCH:
            return (
                f"{label}: beklenen {self.field.expected_display!r}, "
                f"gorulen {self.observed!r}"
            )
        if self.outcome is FieldOutcome.MISSING:
            return (
                f"{label}: belgede bulunamadi ({self.field.json_path}); "
                "protokol uyumu dogrulanamadi"
            )
        if self.outcome is FieldOutcome.UNSUPPORTED:
            return (
                f"{label}: sema bicimi okunamadi ({self.problem}); "
                "protokol uyumu dogrulanamadi"
            )
        return ""


@dataclass(frozen=True, slots=True)
class ProjectionResult:
    """The outcome of comparing the live documents with the expectation."""

    state: DriftState
    observations: tuple[FieldObservation, ...]
    #: Human-readable reasons the state is not ``current``.
    reasons: tuple[str, ...]

    @property
    def critical_mismatches(self) -> tuple[FieldObservation, ...]:
        """Critical fields that are present and different: real drift."""
        return tuple(item for item in self.observations if item.is_critical_mismatch)

    @property
    def critical_unevaluable(self) -> tuple[FieldObservation, ...]:
        """Critical fields that could not be read at all."""
        return tuple(item for item in self.observations if item.is_critical_unevaluable)

    @property
    def critical_failures(self) -> tuple[FieldObservation, ...]:
        """Every critical field that did not match, whatever the reason."""
        return tuple(item for item in self.observations if item.is_critical_failure)

    @property
    def warnings(self) -> tuple[FieldObservation, ...]:
        return tuple(
            item
            for item in self.observations
            if not item.matches and item.field.severity is Severity.WARNING
        )


# ---------------------------------------------------------------------------
# Display and comparison
# ---------------------------------------------------------------------------


def sweep_untrusted(text: str) -> str:
    """Replace invisible characters with a space. No truncation.

    Used before *scanning* a remote description, where a marker hiding past a
    display limit would matter. Display uses :func:`safe_display`.
    """
    return "".join(
        " " if unicodedata.category(character) in _INVISIBLE else character
        for character in text
    )


def safe_display(value: object) -> str:
    """Make a remote value safe to store, log and render.

    Control, format and separator characters become a space, and the result is
    truncated. Level-1 authority means the document is probably accurate; it
    does not mean the bytes are safe to paste into a log line or a UI.

    This is a **display** function. Nothing compares its output: sweeping and
    stripping would make a payload with a trailing newline equal to the
    canonical one, and it is not.
    """
    if isinstance(value, _Absent):
        return MISSING
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    text = (
        ",".join(safe_display(item) for item in value)
        if isinstance(value, list)
        else str(value)
    )

    swept = sweep_untrusted(text).strip()
    if len(swept) > MAX_OBSERVED_CHARS:
        return swept[:MAX_OBSERVED_CHARS] + "..."
    return swept


def _prose_matches(value: str, expected: str) -> bool:
    """Every machine token present as a word, and no negation anywhere."""
    lowered = sweep_untrusted(value).lower()
    if any(
        re.search(rf"\b{re.escape(marker)}\b", lowered) for marker in NEGATION_MARKERS
    ):
        return False
    return all(
        re.search(rf"\b{re.escape(token)}\b", lowered) for token in expected.split()
    )


def _compare(field: ProtocolField, value: object) -> bool:
    """Type-checked comparison against the original value."""
    expected = field.expected

    if field.compare is Compare.TEXT:
        return isinstance(value, str) and value == expected
    if field.compare is Compare.NUMBER:
        # bool is an int subclass and True == 1; a published `true` is not 1.
        return (
            isinstance(value, int) and not isinstance(value, bool) and value == expected
        )
    if field.compare is Compare.MEMBER:
        return isinstance(value, list) and any(
            isinstance(item, str) and item == expected for item in value
        )
    if field.compare is Compare.NAME_SET:
        if not isinstance(value, list) or not all(
            isinstance(item, str) for item in value
        ):
            return False
        return isinstance(expected, tuple) and set(value) == set(expected)
    if field.compare is Compare.PROSE:
        return (
            isinstance(value, str)
            and isinstance(expected, str)
            and _prose_matches(value, expected)
        )
    # Exhaustive. A new comparison mode fails type-checking here rather than
    # silently defaulting to "matches" or "does not match".
    assert_never(field.compare)


# ---------------------------------------------------------------------------
# Extraction
# ---------------------------------------------------------------------------


def _lane_root(field: ProtocolField, document: dict[str, Any]) -> Reading:
    """The node a field's pointer is relative to."""
    if field.lane is Lane.DOCUMENT:
        return Reading(value=document)

    body = read_pointer(document, _LANE_POINTERS[field.lane])
    if isinstance(body, _Absent):
        return Reading()

    if field.lane not in (Lane.MESSAGE_SIGNED, Lane.NOTE_SIGNED):
        return Reading(value=body)

    lane = resolve_signed_lane(body)
    if lane.problem:
        return lane
    node = lane.value
    if not isinstance(node, dict):  # pragma: no cover - resolver guarantees it
        return Reading(problem="imzali lane okunamadi")
    if field.derived is Derived.SIGNED_REQUIRED:
        return Reading(value=node)
    return Reading(value=node["properties"])


def _read(field: ProtocolField, document: dict[str, Any]) -> Reading:
    """Read the value a field describes, including the derived ones."""
    root = _lane_root(field, document)
    if root.problem or isinstance(root.value, _Absent):
        return root

    if field.derived is Derived.LANE_PRESENT:
        return Reading(value=field.expected if isinstance(root.value, dict) else ABSENT)

    if field.derived is Derived.SIGNED_REQUIRED:
        node = root.value
        if not isinstance(node, dict):  # pragma: no cover - guaranteed above
            return Reading()
        required = node.get("required")
        return Reading() if required is None else Reading(value=required)

    value = read_pointer(root.value, field.pointer)
    if (
        field.compare is Compare.PROSE
        and isinstance(value, str)
        and len(sweep_untrusted(value)) > MAX_PROSE_CHARS
    ):
        return Reading(problem="aciklama beklenenden cok uzun, degerlendirilmedi")
    return Reading(value=value)


def _observe(
    field: ProtocolField, documents: dict[SourceId, dict[str, Any]]
) -> FieldObservation:
    document = documents.get(field.source_id)
    if document is None:
        return FieldObservation(
            field=field, observed=MISSING, outcome=FieldOutcome.MISSING
        )

    reading = _read(field, document)
    if reading.problem:
        return FieldObservation(
            field=field,
            observed=safe_display(reading.value),
            outcome=FieldOutcome.UNSUPPORTED,
            problem=reading.problem,
        )
    if isinstance(reading.value, _Absent):
        return FieldObservation(
            field=field, observed=MISSING, outcome=FieldOutcome.MISSING
        )

    outcome = (
        FieldOutcome.MATCHED if _compare(field, reading.value) else FieldOutcome.MISMATCH
    )
    return FieldObservation(
        field=field, observed=safe_display(reading.value), outcome=outcome
    )


def project(documents: dict[SourceId, dict[str, Any]]) -> ProjectionResult:
    """Compare the live documents with the expected contract.

    ``documents`` holds only the sources that parsed. Three outcomes:

    * a critical field present and different is **drift**;
    * a critical field that could not be read is **unavailable** - the check
      did not complete, and saying more than that would be a claim about the
      server that the evidence does not support;
    * otherwise **current**, with any warnings listed beside it.

    Drift wins over unavailable: a real, readable change is the more specific
    answer and the more useful one. Either way ``manifest_current`` is false.
    """
    observations = tuple(_observe(field, documents) for field in PROTOCOL_FIELDS)

    mismatches = [item for item in observations if item.is_critical_mismatch]
    if mismatches:
        return ProjectionResult(
            state=DriftState.DRIFTED,
            observations=observations,
            reasons=tuple(item.reason for item in mismatches),
        )

    unevaluable = [item for item in observations if item.is_critical_unevaluable]
    if unevaluable:
        return ProjectionResult(
            state=DriftState.UNAVAILABLE,
            observations=observations,
            reasons=tuple(item.reason for item in unevaluable),
        )

    return ProjectionResult(
        state=DriftState.CURRENT, observations=observations, reasons=()
    )


def unavailable(reasons: tuple[str, ...]) -> ProjectionResult:
    """A verdict for a check that could not be completed."""
    return ProjectionResult(
        state=DriftState.UNAVAILABLE, observations=(), reasons=reasons
    )


__all__ = [
    "ABSENT",
    "AMBIGUOUS_KEYWORDS",
    "EXPECTED_DID_CHARS",
    "EXPECTED_DID_PATTERN",
    "EXPECTED_NAME_PATTERN",
    "EXPECTED_NONCE_PATTERN",
    "EXPECTED_SIGNATURE_PATTERN",
    "MAX_OBSERVED_CHARS",
    "MAX_PROSE_CHARS",
    "MESSAGE_BODY_POINTER",
    "MISSING",
    "NEGATION_MARKERS",
    "NOTE_BODY_POINTER",
    "PINNED_SERVICE_VERSION",
    "PROTOCOL_FIELDS",
    "Compare",
    "Derived",
    "DriftState",
    "FieldObservation",
    "FieldOutcome",
    "Lane",
    "ProjectionResult",
    "ProtocolField",
    "Reading",
    "Severity",
    "pointer_text",
    "project",
    "read_pointer",
    "resolve_signed_lane",
    "safe_display",
    "sweep_untrusted",
    "unavailable",
]
