"""The task workspace, and the four ways out of it that are closed.

    <data_dir>/workspace/v1/<32-hex task id>/

The layout follows :mod:`station_api.vault.paths`: **versioned**, so a later
format can migrate without ambiguity, and addressed by an
**application-validated identifier** rather than by anything a request said.
A task id is a 32-character lowercase hex string generated by
``uuid4().hex``; it is re-validated here before it is placed in a path, so it
cannot carry a separator or a traversal segment even if a row were edited by
hand.

Putting it under the data directory buys a test for free:
``test_no_plaintext_artefact_is_left_in_the_data_directory`` reads **every
file** under that root and asserts the seed is in none of them, so workspace
files enter the seed scan - and the API-key canary scan beside it -
automatically rather than by somebody remembering to add a path.

There was no precedent for the rest of this file
-------------------------------------------------
Nothing in this repository had defended a directory before. Station hands
files to the browser instead of writing to a path a user chose
(``downloads.py``), the vault writes one file it names itself, and neither
faced traversal, a symbolic link or an archive. So the defences below are
written from nothing, and each one is a *layer*, not a re-statement:

**1. The name is rebuilt, not filtered.** Every file name goes through
``downloads.safe_download_filename``: an allow-list of
``[A-Za-z0-9._-]``, a stem cap, a suffix cap and the Windows reserved device
names. ``..``, ``/``, ``\\``, a drive letter and a NUL cannot survive it,
because they are not on the list. A name that sanitises to something else is
**refused** rather than silently renamed: a run that asked for ``a/b.txt``
and got ``a-b.txt`` would have been given a file it did not ask for, and the
digest it later verifies would be of the wrong thing.

**2. The result is resolved and contained.** ``resolve()`` then
``is_relative_to(root.resolve())`` on **every** read and **every** write,
never once at the top. Resolution is what turns a name that survived layer 1
into the actual path the OS would open, and containment is what refuses the
ones that leave.

**3. Reparse points are refused, all the way up.** A symbolic link or an NTFS
junction anywhere between the workspace root and the file makes containment a
lie: ``resolve()`` follows it, and a link planted by something else on this
machine would point the write anywhere. Every component from the file up to
the root is checked with ``is_symlink()`` **and** ``os.path.isjunction()`` -
Windows junctions are not symbolic links and ``Path.is_symlink`` answers
``False`` for them, which is the exact hole a check written on POSIX habits
would leave. Nothing here ever *creates* a link either: there is no
``symlink_to``, ``os.symlink`` or ``os.link`` in this package, and a test
reads the syntax tree to say so.

**4. There is no archive path at all.** No ``zipfile``, no ``tarfile``, no
``shutil.unpack_archive``, no ``gzip``. This is a deliberate absence rather
than a hardened implementation: zip-slip is a bug class you cannot have if
you never unpack anything, and the cost of not having it is that a user
extracts their own archive, once, outside this product.

Ceilings, because a run that fills a disk is a run that broke the machine
-------------------------------------------------------------------------
:data:`MAX_FILES`, :data:`MAX_FILE_BYTES` and :data:`MAX_TOTAL_BYTES` are
checked **before** the bytes are written, against the directory as it is on
disk rather than against a counter the runner keeps: a counter and a
directory can disagree, and only one of them is what the user has.

The directory ACL follows SI-265's shape
-----------------------------------------
The directory is restricted to SYSTEM and the current user, and so is each
file, on the same call that creates it. Workspace files are not secrets - a
report is meant to be read - so this is defence in depth rather than a trust
boundary, and it is written as such rather than described as one.
"""

from __future__ import annotations

import hashlib
import os
import re
from dataclasses import dataclass
from pathlib import Path

from station_api.agent.errors import WorkspaceError
from station_api.downloads import safe_download_filename, split_suffix

# One of exactly two names this package takes from ``station_api.vault``, and
# both are spelled at full module depth on purpose. ADR-0008 7 carries
# SI-213's rule into this package: the agent reaches no vault, no signer and
# no credential. ``windows_acl`` is a filesystem helper that happens to live
# in that directory - it touches no key material, opens no envelope and holds
# no secret - and ``vault.errors`` is exception classes. A test pins the
# allow-list at those two modules, so the exemption cannot widen: an import
# of ``vault.service``, ``vault.dpapi`` or ``vault.passphrase`` fails it.
from station_api.vault.windows_acl import is_windows, restrict_to_current_user

WORKSPACE_DIRNAME = "workspace"
WORKSPACE_FORMAT_DIRNAME = "v1"

#: Most files one task's workspace may hold.
MAX_FILES = 64

#: Largest single file, in bytes.
MAX_FILE_BYTES = 512 * 1024

#: Largest total, in bytes, across one task's workspace.
MAX_TOTAL_BYTES = 4 * 1024 * 1024

_TASK_ID_RE = re.compile(r"\A[0-9a-f]{32}\Z")


@dataclass(frozen=True, slots=True)
class WorkspaceFile:
    """One file, as far as anything outside this module needs to know."""

    name: str
    byte_count: int
    sha256: str


def validate_task_id(task_id: str) -> str:
    """Refuse anything that is not a bare 32-char lowercase hex id.

    ``vault.paths.validate_identity_id``'s rule, applied to the other
    application-generated identifier that reaches a path.
    """
    if not isinstance(task_id, str) or not _TASK_ID_RE.match(task_id):
        raise WorkspaceError(
            "Calisma alani kimligi uygulama tarafindan uretilmis bir deger "
            "olmali.",
            reason="workspace_id_invalid",
        )
    return task_id


def workspace_root(data_dir: Path) -> Path:
    """``<data_dir>/workspace/v1``. Never derived from a request."""
    return data_dir / WORKSPACE_DIRNAME / WORKSPACE_FORMAT_DIRNAME


def task_workspace(data_dir: Path, task_id: str) -> Path:
    """One task's directory. The id is validated before it becomes a path."""
    return workspace_root(data_dir) / validate_task_id(task_id)


def safe_name(raw: str) -> str:
    """Rebuild a file name from the allow-list, or refuse it.

    Refusal rather than rename is the decision worth reading twice. The
    download header can rename freely: a browser save dialog showing
    ``rapor-1.json`` instead of ``rapor/1.json`` loses nothing. A workspace
    cannot, because the run goes on to hash that file and compare the digest,
    and a silent rename would make the comparison be about a different file
    than the one the plan named.
    """
    stem, suffix = split_suffix(raw)
    rebuilt = safe_download_filename(stem, suffix=suffix)
    if rebuilt != raw:
        raise WorkspaceError(
            "Dosya adi kabul edilmedi. Yalnizca harf, rakam, nokta, tire ve "
            "alt cizgi kullanilabilir; yol ayraci, surucu harfi ve '..' "
            "yazilamaz.",
            reason="workspace_name_refused",
        )
    return rebuilt


def _assert_no_reparse_point(root: Path, candidate: Path) -> None:
    """Refuse a symbolic link or junction anywhere from ``candidate`` up to ``root``.

    Walked upwards rather than checked on the leaf, because a link one
    directory above the file redirects the write just as completely. The two
    predicates are both needed on Windows: ``is_symlink`` answers ``False``
    for an NTFS junction, and a junction is the reparse point an unprivileged
    user can actually create.
    """
    current = candidate
    while True:
        if current.is_symlink() or os.path.isjunction(current):
            raise WorkspaceError(
                "Calisma alaninda bir baglanti (symlink/junction) var; "
                "baglanti uzerinden okuma ve yazma reddedilir.",
                reason="workspace_reparse_point",
            )
        if current == root or current.parent == current:
            return
        current = current.parent


def resolve_within(root: Path, raw_name: str) -> Path:
    """The one function that turns a name into a path inside a workspace.

    Both layers, in order, on every call: the name is rebuilt from the
    allow-list, then the result is resolved and required to be inside the
    resolved root. Callers do not get to skip either, because callers do not
    get a path any other way.
    """
    name = safe_name(raw_name)
    resolved_root = root.resolve()
    candidate = (resolved_root / name).resolve()
    if not candidate.is_relative_to(resolved_root):
        raise WorkspaceError(
            "Dosya calisma alaninin disina cikiyor.",
            reason="workspace_escape",
        )
    if candidate == resolved_root:
        raise WorkspaceError(
            "Dosya adi bir dizin adi olamaz.",
            reason="workspace_name_refused",
        )
    return candidate


def ensure_workspace(data_dir: Path, task_id: str) -> Path:
    """Create one task's directory, restricted, and hand back its path."""
    directory = task_workspace(data_dir, task_id)
    directory.mkdir(parents=True, exist_ok=True)
    _restrict(directory)
    _assert_no_reparse_point(workspace_root(data_dir).resolve(), directory.resolve())
    return directory


def _restrict(path: Path) -> None:
    """Apply the restrictive DACL where the platform has one.

    Silent on non-Windows, because there is no equivalent to apply and the
    POSIX branch exists only so the suite can run off-Windows (ADR-008:
    Windows-only MVP). It is *not* silent about a failure on Windows: an ACL
    that could not be applied raises, exactly as the vault's does.
    """
    if is_windows():
        restrict_to_current_user(path)


def list_files(directory: Path) -> tuple[WorkspaceFile, ...]:
    """Every file in one workspace, with its size and digest, sorted by name.

    Non-files are ignored and links are refused: a listing that walked a
    junction would report files that are not in this workspace at all.
    """
    if not directory.is_dir():
        return ()
    root = directory.resolve()
    found: list[WorkspaceFile] = []
    for entry in sorted(root.iterdir(), key=lambda path: path.name):
        if entry.is_symlink() or os.path.isjunction(entry):
            raise WorkspaceError(
                "Calisma alaninda bir baglanti (symlink/junction) var; "
                "baglanti uzerinden okuma ve yazma reddedilir.",
                reason="workspace_reparse_point",
            )
        if not entry.is_file():
            continue
        payload = entry.read_bytes()
        found.append(
            WorkspaceFile(
                name=entry.name,
                byte_count=len(payload),
                sha256=hashlib.sha256(payload).hexdigest(),
            )
        )
    return tuple(found)


def total_bytes(directory: Path) -> int:
    """What this workspace holds right now. Read from disk, never counted."""
    return sum(item.byte_count for item in list_files(directory))


def read_text(directory: Path, name: str) -> str:
    """Read one workspace file as UTF-8, or refuse.

    The same two layers a write goes through, plus the reparse walk: a read
    that followed a link would let a planted link exfiltrate a file from
    anywhere this process can reach into a report the user then publishes.
    """
    root = directory.resolve()
    target = resolve_within(root, name)
    _assert_no_reparse_point(root, target)
    if not target.is_file():
        raise WorkspaceError(
            "Calisma alaninda bu adda bir dosya yok.",
            reason="workspace_file_missing",
        )
    payload = target.read_bytes()
    if len(payload) > MAX_FILE_BYTES:
        raise WorkspaceError(
            "Dosya okunabilir boyut tavanini asiyor.",
            reason="workspace_file_too_large",
        )
    try:
        return payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise WorkspaceError(
            "Dosya UTF-8 metin degil; bu surumde yalnizca metin okunur.",
            reason="workspace_not_text",
        ) from exc


def write_text(
    directory: Path, name: str, body: str, *, replace_existing: bool
) -> WorkspaceFile:
    """Write one UTF-8 file inside the workspace, under every ceiling.

    ``replace_existing`` is a required keyword and has no default. "Create"
    and "overwrite" are two different intentions and the registry exposes
    them as two different tools; a default here would let one of them be
    reached without anybody having chosen it.

    The ceilings are checked against the directory **as it is**, immediately
    before the write, so a run cannot pass a stale count.
    """
    root = directory.resolve()
    target = resolve_within(root, name)
    _assert_no_reparse_point(root, target)

    payload = body.encode("utf-8")
    if len(payload) > MAX_FILE_BYTES:
        raise WorkspaceError(
            f"Dosya {MAX_FILE_BYTES} bayt tavanini asiyor.",
            reason="workspace_file_too_large",
        )

    existing = list_files(directory)
    by_name = {item.name: item for item in existing}
    if target.name in by_name and not replace_existing:
        raise WorkspaceError(
            "Bu adda bir dosya zaten var; uzerine yazmak ayri bir aractir.",
            reason="workspace_file_exists",
        )
    if target.name not in by_name:
        if replace_existing:
            raise WorkspaceError(
                "Guncellenecek dosya yok; olmayan bir dosya guncellenmez.",
                reason="workspace_file_missing",
            )
        if len(existing) >= MAX_FILES:
            raise WorkspaceError(
                f"Calisma alani {MAX_FILES} dosya tavanina ulasti.",
                reason="workspace_file_count_exhausted",
            )

    already = sum(
        item.byte_count for item in existing if item.name != target.name
    )
    if already + len(payload) > MAX_TOTAL_BYTES:
        raise WorkspaceError(
            f"Calisma alani {MAX_TOTAL_BYTES} bayt tavanini asardi.",
            reason="workspace_total_bytes_exhausted",
        )

    _write_bytes(target, payload)
    return WorkspaceFile(
        name=target.name,
        byte_count=len(payload),
        sha256=hashlib.sha256(payload).hexdigest(),
    )


def _write_bytes(target: Path, payload: bytes) -> None:
    """Create the file empty, restrict it, then write - SI-265's ordering.

    The credential store measured this once and found 537 bytes already on
    disk under an inherited DACL while the ACL call was still pending. These
    bytes are not a credential, so the impact would be lower, but the
    ordering costs nothing and a file that is protected from its first byte
    needs no argument about which bytes were exposed.
    """
    flags = os.O_CREAT | os.O_TRUNC | os.O_WRONLY
    binary = getattr(os, "O_BINARY", 0)
    handle = os.open(target, flags | binary, 0o600)
    try:
        with os.fdopen(handle, "wb") as stream:
            _restrict(target)
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
    except BaseException:
        target.unlink(missing_ok=True)
        raise


def digest_of(directory: Path, name: str) -> str:
    """The SHA-256 of one workspace file, through the same two layers."""
    root = directory.resolve()
    target = resolve_within(root, name)
    _assert_no_reparse_point(root, target)
    if not target.is_file():
        raise WorkspaceError(
            "Calisma alaninda bu adda bir dosya yok.",
            reason="workspace_file_missing",
        )
    return hashlib.sha256(target.read_bytes()).hexdigest()


__all__ = [
    "MAX_FILES",
    "MAX_FILE_BYTES",
    "MAX_TOTAL_BYTES",
    "WORKSPACE_DIRNAME",
    "WORKSPACE_FORMAT_DIRNAME",
    "WorkspaceFile",
    "digest_of",
    "ensure_workspace",
    "list_files",
    "read_text",
    "resolve_within",
    "safe_name",
    "task_workspace",
    "total_bytes",
    "validate_task_id",
    "workspace_root",
    "write_text",
]
